NAME="Agricultural Science"
Q=[
("Agriculture is best defined as the production of","money from banks|crops and animals for man's use|cars and roads|clothing only",1,"Crop and animal production for food and industry.","Meaning and importance"),
("Pomology is the branch of horticulture dealing with","fruits|vegetables|flowers|ornamental lawns",0,"Pomology = fruit growing.","Branches of agriculture"),
("Olericulture covers the production of","fruits|vegetables|flowers|spices only",1,"Olericulture = vegetable growing.","Branches of agriculture"),
("Crop rotation mainly helps to","exhaust soil nutrients|maintain soil fertility and break pest cycles|increase weeds|lower yields",1,"Alternating crops manages fertility and pests.","Farming systems"),
("The taungya system combines","fishing and hunting|forestry with arable cropping by farmers|poultry and pigs|irrigation and drainage",1,"Farmers raise food crops among young forest trees.","Farming systems"),
("Nomadic herding is problematic in modern Nigeria mainly because","cattle refuse grass|it causes overgrazing and farmer–herder conflicts|it is too cheap|herders use tractors",1,"Uncontrolled movement strains land and relations.","Farming systems"),
("Communal land tenure hinders commercial farming because land","cannot be sold or easily consolidated|is too fertile|belongs to banks|is surveyed yearly",0,"Fragmentation and ownership limits deter investment.","Land tenure"),
("The Land Use Act of 1978 vested land in Nigeria in","state governors|traditional rulers|farmers|foreign firms",0,"Governors hold land in trust for the people.","Land tenure"),
("Weather elements affecting crop production include all EXCEPT","rainfall|temperature|soil pH of rocks — unrelated to weather|sunshine",2,"pH is a soil property, not a weather element.","Agro-climatology"),
("Soil is formed through the interaction of parent material, climate, organisms, topography and","time|machinery|fertiliser price|rain gutters",0,"The five soil-forming factors.","Soil science"),
("Mineral matter makes up about ___ of the volume of a typical soil.","25%|45%|90%|5%",1,"45% mineral, 5% organic, 25% water, 25% air.","Soil science"),
("The ideal farm soil texture is","heavy clay|loam|pure sand|gravel",1,"Loam balances water, air and nutrients.","Soil science"),
("The best soil structure for crop growth is usually","blocky|crumb|prismatic|platy",1,"Crumb (granular) structure gives good tilth.","Soil science"),
("Hygroscopic water in soil is","available to plants|held so tightly it is unavailable to plants|drainage water|vapour only",1,"Bound to particles, unusable by roots.","Soil water"),
("Soil pH of most crops is optimum around","3–4|6–7|9–10|12",1,"Slightly acid to neutral suits most crops.","Soil chemistry"),
("Ground limestone is applied to acid soils to","lower pH|raise pH|kill insects|add nitrogen",1,"Liming neutralises acidity.","Soil chemistry"),
("Yellowing of older leaves (chlorosis) suggests deficiency of","nitrogen|potassium|calcium|boron",0,"N is mobile and moves to young leaves, old ones yellow.","Plant nutrition"),
("Purple colouration and stunting in crops indicate deficiency of","phosphorus|nitrogen|chlorine|copper",0,"P deficiency shows purple tints.","Plant nutrition"),
("NPK 15-15-15 fertiliser contains","15% each of N, P₂O₅ and K₂O|15 kg only|15 elements|only nitrogen",0,"The numbers are percentages of N, P₂O₅, K₂O.","Fertilisers"),
("Urea's nitrogen content is about","21%|46%|82%|11%",1,"Urea (46% N) is the richest solid N source.","Fertilisers"),
("Compost is ready for use after about","2 days|6–8 weeks of proper layering and turning|5 years|1 hour",1,"Decomposition with turning matures in weeks.","Manures"),
("Green manure refers to","dried leaves|young green crops ploughed into the soil|painted grass|compost tea",1,"Legumes ploughed under add organic matter and N.","Manures"),
("Mulching benefits the soil by","increasing erosion|conserving moisture and checking weeds|heating soil at noon|adding stones",1,"Mulch covers and protects.","Soil conservation"),
("Windbreaks control","soil erosion by wind|floods|weeds|pests only",0,"Tree lines shield fields from wind.","Soil conservation"),
("The most water-efficient irrigation method is","flood|sprinkler|drip|furrow",2,"Drip targets roots with minimal loss.","Irrigation"),
("Waterlogged soil harms crops chiefly because","roots drown for lack of air|water is dirty|soil warms|nutrients double",0,"Poor aeration starves roots.","Drainage"),
("Ploughing is a primary tillage operation, while harrowing is","primary too|secondary, breaking clods into fine tilth|planting|harvesting",1,"Harrowing follows ploughing for seedbed fineness.","Land preparation"),
("Ridging is especially useful for","root crops like yam and erosion control|rice only|poultry|fish ponds",0,"Ridges suit tubers and check erosion.","Land preparation"),
("Advantages of nursery-raised seedlings include","weaker plants|careful early management and transplanting of delicate crops|no watering|no soil needed",1,"Tomatoes, tobacco, oil palm are transplanted.","Propagation"),
("Vegetative propagation of cassava uses","stem cuttings|seeds|roots only|budding",0,"Mature stem cuttings planted directly.","Propagation"),
("Citrus is commonly propagated by","budding|stem cuttings|seeds only|rhizomes",0,"Buds join scion to resistant rootstock.","Propagation"),
("Banana is propagated by means of","suckers|seeds|cuttings|layers",0,"Sword suckers from the mother corm.","Propagation"),
("Yam minisett technique involves planting","whole large tubers|small healthy sett pieces of about 25–100 g|leaves|flowers",1,"Cut setts treated and planted to multiply seed yam.","Propagation"),
("Sexual propagation from seeds produces","identical offspring|variation among offspring|no roots|clones",1,"Segregation yields variable plants.","Propagation"),
("Which is a cereal crop?","groundnut|millet|cassava|cocoa",1,"Millets are cereals (maize, rice, sorghum, millet).","Crop classification"),
("Leguminous crops like cowpea improve soil by","nitrogen fixation via root nodules|adding sand|drying soil|attracting rain",0,"Rhizobium fixes N₂ in nodules.","Crop classification"),
("Groundnut is grown mainly for","timber|oil and protein-rich seeds|latex|fibre",1,"Oil seeds plus fodder.","Crop classification"),
("Sisal and cotton are classified as","beverage crops|fibre crops|cereals|spices",1,"They yield industrial fibre.","Crop classification"),
("Speargrass (Imperata cylindrica) is a troublesome weed because it","fixes nitrogen|spreads by rhizomes and competes severely|cures disease|hosts bees",1,"Underground rhizomes regenerate fast.","Weeds"),
("Water hyacinth is a menace on Nigerian waterways because it","purifies water|chokes water surfaces, hindering transport and fishing|increases fish|stabilises banks",1,"Rapidly multiplying floating mats.","Weeds"),
("A selective herbicide","kills all plants|kills only certain weeds, sparing the crop|feeds crops|kills animals",1,"Selective chemicals target weed species.","Weed control"),
("The maize stem borer is controlled partly by early planting because","attack is avoided at peak flight|borers die in sun|rain drowns them|maize grows taller",0,"Escaping the pest's peak reduces damage.","Pests"),
("Quelea birds are notorious pests of","cattle|rice, sorghum and millet fields|fish|trees",1,"Flocks devastate grain heads.","Pests"),
("Weevils and the larger grain borer attack crops","in the field only|in storage|in nurseries|in rivers",1,"Stored grain pests cause post-harvest losses.","Pests"),
("Integrated Pest Management (IPM) combines methods and uses chemicals","as the first resort|only when necessary, minimising them|never|weekly regardless",1,"Chemicals are a last resort within IPM.","Pest control"),
("Cassava mosaic disease is caused by a","fungus|virus|bacterium|nematode",1,"CMD is viral, spread by whiteflies and cuttings.","Diseases"),
("Late blight, the historic potato disease, is caused by","Phytophthora (a fungus-like organism)|a virus|a bacterium|birds",0,"Phytophthora infestans devastated Ireland.","Diseases"),
("Using certified seed and resistant varieties controls disease by","feeding pests|avoiding infected planting material|warming soil|adding water",1,"Clean planting material prevents carryover.","Disease control"),
("Grain stored safely should have moisture content around","25–30%|12–13%|50%|70%",1,"Dry grain resists mould and pests.","Storage"),
("Aflatoxin contamination results from","moulds on poorly dried grain|too much sun|cold storage|clean mills",0,"Aspergillus flavus on damp grain is dangerous.","Storage"),
("Garri production from cassava involves","roasting only|fermentation and frying of grated mash|smoking leaves|boiling whole tubers",1,"Peel-grate-ferment-fry gives garri.","Processing"),
("Ruminants digest cellulose efficiently because the rumen hosts","viruses|microbes that ferment cellulose|stones|air bubbles",1,"Bacteria and protozoa break down fibre.","Animal nutrition"),
("The 'true stomach' of a ruminant is the","rumen|abomasum|reticulum|omasum",1,"The abomasum secretes gastric juice.","Animal anatomy"),
("Bloat in cattle results from","excess water drinking|eructation failure — trapped fermentation gas|cold weather|too much walking",1,"Gas cannot be belched out; frothy feed worsens it.","Animal health"),
("Broilers reach market weight of about 2 kg in roughly","2 weeks|6–8 weeks|6 months|1 year",1,"Fast meat strains finish in under two months.","Poultry"),
("The incubation period of a hen's egg is","18 days|21 days|28 days|30 days",1,"Chicks hatch on day 21.","Poultry"),
("Layers begin laying around ___ weeks of age.","8–10|18–20|40|52",1,"Point-of-lay comes near 18–20 weeks.","Poultry"),
("Oyster shell is fed to layers mainly to supply","calcium for eggshells|protein|energy|vitamins",0,"Ca carbonate builds shells.","Poultry"),
("Newcastle disease in poultry is prevented by","vaccination|fresh grass|antibiotics only|wing clipping",0,"Routine vaccination schedules.","Animal health"),
("A sow's gestation lasts about","114 days|283 days|150 days|365 days",0,"Three months, three weeks, three days.","Livestock"),
("The gestation period of a cow is about","150 days|283 days|114 days|60 days",1,"About nine months.","Livestock"),
("Trypanosomiasis in cattle is transmitted by","ticks|tsetse flies|mosquitoes|fleas",1,"Tsetse flies carry the trypanosome.","Animal health"),
("Ticks are controlled mainly by","dipping or spraying with acaricides|feeding more hay|singing|weeding",0,"Acaricides kill ectoparasites.","Animal health"),
("The main aim of quarantine in animal health is to","feed animals|isolate and observe new animals for disease before mixing|breed faster|fatten",1,"It prevents disease introduction.","Animal health"),
("Aquaculture differs from capture fisheries because fish are","hunted at sea|reared in controlled ponds or tanks|imported|frozen only",1,"Culture systems manage the whole life cycle.","Fisheries"),
("Afforestation means","cutting old forest|establishing new forest where none was|burning bush|farming trees for food only",1,"New forest on formerly treeless land.","Forestry"),
("Deforestation leads to","soil erosion, loss of biodiversity and climatic change|more rain|richer soil|cleaner rivers",0,"Tree loss degrades land and climate.","Forestry"),
("Alley cropping is an agroforestry system where","crops grow between rows of trees|fish swim in alleys|goats graze roofs|trees are burned",0,"Hedgerows with food crop alleys.","Agroforestry"),
("Simple farm survey tools include","ranging poles and prismatic compass|tractors|drones only|scales",0,"Basic survey sets boundaries and layouts.","Farm surveying"),
("A farm's production records mainly help the farmer","brag|take management decisions and obtain credit|avoid work|cheat buyers",1,"Records guide planning and loans.","Farm records"),
("Middlemen in agricultural marketing are criticised chiefly for","paying farmers more than consumers|taking large margins between farmer and consumer|transporting free|storing for free",1,"They widen the price spread.","Agro-marketing"),
("Commodity boards in the past","bought cash crops from farmers for export|printed money|built airports|ran schools only",0,"They handled cocoa, groundnut, palm produce.","Agro-marketing"),
("Price gluts at harvest occur because","demand exceeds supply at that time|supply peaks while storage is poor|farmers refuse to sell|prices rise then",1,"Perishable peak supply crushes prices.","Agro-marketing")
]
