NAME="Biology"
Q=[
("A cross AaBb × AaBb gives the phenotypic ratio","3:1|9:3:3:1|1:1:1:1|12:3:1",1,"Dihybrid cross of heterozygotes: 9:3:3:1.","Genetics"),
("To determine the genotype of a dominant individual, it is crossed with a","homozygous dominant|homozygous recessive|heterozygote|any pure line",1,"A test cross uses the homozygous recessive.","Genetics"),
("A mother who is a carrier of haemophilia and an unaffected father will pass the condition to","all sons|half the sons|daughters only|no child",1,"Sex-linked recessive: each son has a 50% chance of receiving the affected X.","Genetics"),
("Parents of blood groups AB and O can only have children of blood groups","AB and O|A and B|AB only|all groups",1,"AB parent makes A or B gametes; O parent makes O: children are A or B only.","Genetics"),
("Down's syndrome results from","a gene mutation|trisomy of chromosome 21|absence of an X chromosome|nondisjunction of sex chromosomes",1,"An extra chromosome 21 (trisomy).","Genetics"),
("During which phase of mitosis do sister chromatids separate?","prophase|metaphase|anaphase|telophase",2,"Chromatids move to opposite poles in anaphase.","Cell division"),
("Crossing over, which introduces variation, occurs during","prophase I of meiosis|metaphase II|mitotic prophase|cytokinesis",0,"Chiasmata form in prophase I.","Cell division"),
("The movement of water across a semi-permeable membrane is","diffusion|osmosis|active transport|plasmolysis",1,"Osmosis is the passive movement of the solvent.","Transport in cells"),
("A plant cell placed in a hypertonic solution will","swell|undergo plasmolysis|burst|stay unchanged",1,"Water leaves the cell; the protoplast shrinks.","Transport in cells"),
("Active transport differs from diffusion because it moves substances","down the gradient|against the gradient using energy|without a membrane|only in gases",1,"It needs ATP and works against the gradient.","Transport in cells"),
("Enzymes are denatured by temperatures that are","too low|too high|constant|body-like",1,"High temperature destroys the tertiary structure.","Enzymes"),
("The optimum pH for pepsin is about","2|7|9|5",0,"Pepsin works in the acidic stomach.","Enzymes"),
("A competitive inhibitor acts by","binding the active site|changing the substrate|denaturing the enzyme|raising temperature",0,"It competes with the substrate for the active site.","Enzymes"),
("The light-dependent stage of photosynthesis produces","glucose|ATP and oxygen|carbon dioxide|water",1,"Photolysis of water releases O₂ while ATP and NADPH form.","Photosynthesis"),
("Chlorophyll appears green because it","absorbs green light|reflects green light|transmits red light|contains magnesium",1,"Green is reflected to the eye.","Photosynthesis"),
("Water and mineral salts move up the xylem mainly because of","root pressure alone|transpiration pull and cohesion|osmotic push|active transport in leaves",1,"Cohesion-tension theory.","Plant transport"),
("Sugars are moved around the plant in the","xylem|phloem|cambium|pith",1,"Phloem translocates sucrose from source to sink.","Plant transport"),
("Transpiration is fastest when humidity is","high|low|100%|zero wind with high humidity",1,"Low humidity steepens the water-vapour gradient.","Plant transport"),
("Stomata close when the guard cells are","turgid|flaccid|dividing|photosynthesising fast",1,"Loss of turgor closes the pore.","Plant transport"),
("The products of anaerobic respiration in yeast are","water and CO₂|alcohol and CO₂|lactic acid and water|ammonia and CO₂",1,"Fermentation gives ethanol + carbon dioxide.","Respiration"),
("The respiratory quotient of fats is about","1|0.7|1.3|0",1,"Fats need more oxygen per molecule: RQ ≈ 0.7.","Respiration"),
("Salivary amylase converts starch to","glucose|maltose|peptides|fatty acids",1,"Amylase breaks starch into maltose.","Digestion"),
("Pepsin is activated by","bile|hydrochloric acid|amylase|mucus",1,"HCl creates the acidic environment pepsin needs.","Digestion"),
("Bile helps digestion by","digesting proteins|emulsifying fats|absorbing glucose|killing bacteria",1,"Emulsification increases fat surface area.","Digestion"),
("The surface area for absorption in the small intestine is increased by","villi and microvilli|more acid|longer colon|the stomach",0,"Villi plus microvilli enormously increase area.","Digestion"),
("The hepatic portal vein carries","oxygenated blood to the liver|nutrient-rich blood to the liver|waste to the kidneys|blood from the lungs",1,"It transports absorbed nutrients from the gut to the liver.","Circulation"),
("ADH increases water reabsorption in the kidney by acting on the","glomerulus|collecting duct|bladder|ureter",1,"ADH makes the collecting duct more permeable.","Homeostasis"),
("Insulin is secreted by the","α-cells of the pancreas|β-cells of the pancreas|liver|pituitary",1,"Beta cells of the islets secrete insulin.","Homeostasis"),
("Homeostasis is maintained mainly by","positive feedback|negative feedback|random fluctuation|hormone excess",1,"Negative feedback reverses deviations.","Homeostasis"),
("The functional unit of the kidney is the","neuron|nephron|alveolus|glomerulus only",1,"Each kidney has about a million nephrons.","Excretion"),
("Ultrafiltration occurs in the","glomerulus|loop of Henle|urethra|capsule only",0,"High pressure in the glomerulus filters plasma.","Excretion"),
("Selective reabsorption of glucose mainly occurs in the","proximal convoluted tubule|collecting duct|ureter|bladder",0,"The PCT reclaims glucose and salts.","Excretion"),
("The myelin sheath speeds nerve transmission by","saltatory conduction|slowing leakage|cooling the axon|increasing diameter",0,"Impulses jump node to node.","Nervous coordination"),
("Transmission across a synapse occurs by means of","direct electric current|a neurotransmitter|osmosis|blood flow",1,"Chemicals like acetylcholine cross the gap.","Nervous coordination"),
("The correct reflex arc order is","effector→motor→CNS→sensory→receptor|receptor→sensory→CNS→motor→effector|receptor→motor→sensory→CNS|CNS→receptor→effector",1,"Impulse: receptor to effector via the CNS.","Nervous coordination"),
("Adrenaline prepares the body for 'fight or flight' by","slowing the heart|raising blood glucose and heart rate|constricting the bronchi|lowering pressure",1,"It mobilises glucose and stimulates the heart.","Hormonal coordination"),
("Auxin causes cell elongation in shoots, and shoots bend towards light because auxin","moves to the lit side|moves to the shaded side|is destroyed by light|diffuses evenly",1,"Auxin accumulates on the shaded side, elongating those cells.","Plant responses"),
("Energy flow between trophic levels is about","10%|50%|90%|100%",0,"Only ~10% passes to the next level.","Ecology"),
("Bacteria of the genus Rhizobium are important in the nitrogen cycle because they","nitrify ammonia|fix atmospheric nitrogen|denitrify|decay proteins",1,"They fix N₂ in root nodules of legumes.","Ecology"),
("Denitrifying bacteria convert","ammonia to nitrite|nitrates to nitrogen gas|nitrogen to ammonia|uric acid to urea",1,"They return nitrogen gas to the atmosphere.","Ecology"),
("Combustion and respiration return ___ to the carbon cycle.","oxygen|carbon dioxide|nitrogen|methane only",1,"Both processes release CO₂.","Ecology"),
("An organism's niche is best described as its","address|functional role in the ecosystem|taxonomic rank|population size",1,"Habitat is the address; the niche is the profession.","Ecology"),
("In mutualism,","both organisms benefit|one benefits, other unaffected|one is harmed|neither benefits",0,"Both partners gain.","Ecology"),
("Eutrophication begins when fertiliser run-off causes","oxygen depletion|a rise in pH only|toxic mercury|erosion",0,"Algal blooms die and decompose, exhausting oxygen.","Ecology"),
("The climax community is the","first coloniser|final stable stage of succession|middle stage|bare rock",1,"Succession ends in a stable climax.","Ecology"),
("Double fertilisation in flowering plants produces","two embryos|the embryo and the endosperm|twin seeds|a fruit and no seed",1,"One sperm forms the embryo; the other forms the endosperm.","Reproduction"),
("Fertilisation in humans normally occurs in the","uterus|oviduct|ovary|cervix",1,"It happens in the fallopian tube.","Reproduction"),
("Ovulation is triggered by a surge of","FSH|LH|oestrogen|progesterone",1,"The mid-cycle LH surge releases the ovum.","Reproduction"),
("The unique distinguishing feature of birds is","feathers|flight|beaks|warm blood",0,"Only birds have feathers.","Classification"),
("Natural selection requires variation, overproduction and","extinction|survival of the fittest|mutation only|artificial breeding",1,"Differential survival of better-adapted variants drives evolution.","Evolution")
]
