NAME="Chemistry"
Q=[
("How many moles are present in 44 g of CO₂? (C = 12, O = 16)","1|2|0.5|4",0,"Molar mass 44 → 44/44 = 1 mol.","Mole concept"),
("Find the molar mass of CaCO₃. (Ca = 40, C = 12, O = 16)","84 g|100 g|96 g|112 g",1,"40 + 12 + 48 = 100 g.","Mole concept"),
("What volume does 0.5 mol of gas occupy at STP? (molar volume 22.4 dm³)","11.2 dm³|22.4 dm³|44.8 dm³|5.6 dm³",0,"0.5 × 22.4 = 11.2 dm³.","Mole concept"),
("Find the percentage by mass of nitrogen in NH₄NO₃. (H = 1, N = 14, O = 16)","35%|46.7%|28%|17.5%",0,"2(14)/80 = 35%.","Mole concept"),
("An organic compound is found to contain 40% carbon, 6.7% hydrogen and 53.3% oxygen. Its empirical formula is","CH₂O|C₂H₄O|CHO|CH₃O",0,"Ratio C:H:O ≈ 1:2:1 → CH₂O.","Mole concept"),
("In the reaction 2H₂ + O₂ → 2H₂O, 8 g of H₂ is mixed with 32 g of O₂. The limiting reagent is","H₂|O₂|neither|both equally",1,"8 g H₂ = 4 mol needs 2 mol O₂ (64 g); only 32 g present, so O₂ limits.","Stoichiometry"),
("How many particles are in 0.25 mol of a substance? (Avogadro 6.02 × 10²³)","1.505 × 10²³|6.02 × 10²³|3.01 × 10²³|2.408 × 10²⁴",0,"0.25 × 6.02 × 10²³ = 1.505 × 10²³.","Mole concept"),
("At constant temperature, if the pressure on a fixed mass of gas is doubled, its volume","doubles|halves|quadruples|stays the same",1,"Boyle's law: pressure and volume are inversely related.","Gas laws"),
("At constant volume, the pressure of a fixed mass of gas is directly proportional to its absolute temperature. This is","Boyle's law|Charles' law|Gay-Lussac's law|Avogadro's law",2,"Pressure law (Gay-Lussac).","Gas laws"),
("In PV = nRT, if P is in atmospheres and V in dm³, then R equals","8.31 J/K|0.082 atm·dm³/K|1.987 cal/K|62.4 L·mmHg/K",1,"R = 0.0821 atm dm³ K⁻¹ mol⁻¹ with those units.","Gas laws"),
("For N₂ + 3H₂ ⇌ 2NH₃, the equilibrium constant Kc equals","[NH₃]²/[N₂][H₂]³|[NH₃]² × [N₂][H₂]³|[N₂][H₂]³/[NH₃]²|2[NH₃]/[N₂]3[H₂]",0,"Products over reactants with stoichiometric powers.","Chemical equilibrium"),
("Increasing the pressure in the Haber process N₂ + 3H₂ ⇌ 2NH₃ shifts equilibrium","to the left|to the right|no shift|depends on catalyst",1,"Fewer gas moles on the right; pressure favours the right.","Chemical equilibrium"),
("Raising the temperature of an equilibrium mixture shifts the position towards","the exothermic direction|the endothermic direction|no direction|the side with more moles only",1,"Heat is treated as a reactant for endothermic directions.","Chemical equilibrium"),
("A catalyst added to a system at equilibrium","increases the yield|speeds attainment without changing the position|shifts it right|slows the reverse reaction",1,"Catalysts affect rate both ways, not the position.","Chemical equilibrium"),
("The pH of a 0.01 M hydrochloric acid solution is","1|2|12|0.01",1,"[H⁺] = 0.01 → pH = −log(10⁻²) = 2.","Acids and bases"),
("At 25°C, the ionic product of water Kw equals","10⁻⁷|10⁻¹⁴|10⁻¹⁰|1",1,"Kw = [H⁺][OH⁻] = 1 × 10⁻¹⁴.","Acids and bases"),
("The suitable indicator for a strong acid–strong base titration is","methyl orange only|phenolphthalein|litmus only|none",1,"Endpoint near pH 7; phenolphthalein (range 8.3–10) is standard.","Acids and bases"),
("A buffer solution can be prepared from a","strong acid and its salt|weak acid and its salt|strong base alone|any salt",1,"Weak acid + conjugate salt resists pH change.","Acids and bases"),
("The oxidation number of chromium in K₂Cr₂O₇ is","+3|+6|+7|+2",1,"2(+1) + 2x + 7(−2) = 0 → x = +6.","Redox reactions"),
("The oxidation number of manganese in KMnO₄ is","+7|+6|+5|+4",0,"+1 + x + 4(−2) = 0 → x = +7.","Redox reactions"),
("Oxidation is defined as the","gain of electrons|loss of electrons|gain of protons|loss of neutrons",1,"OIL RIG: oxidation is loss of electrons.","Redox reactions"),
("Zinc displaces copper from copper(II) solution because zinc is","more reactive|heavier|cheaper|a better conductor",0,"Higher metals in the reactivity series displace lower ones.","Redox reactions"),
("During electrolysis, reduction occurs at the","anode|cathode|both electrodes|neither electrode",1,"Cathode: cations gain electrons (reduction).","Electrolysis"),
("What mass of copper is deposited by 9,650 C? (Cu²⁺, eq. mass 31.75, F = 96,500 C)","31.75 g|3.175 g|63.5 g|1.59 g",1,"m = (Q/F) × eq. mass = 0.1 × 31.75 = 3.175 g.","Electrolysis"),
("In the electrolytic refining of copper, the anode is made of","pure copper|impure copper|carbon|platinum",1,"Impure copper dissolves at the anode; pure deposits at the cathode.","Electrolysis"),
("The bleaching action of chlorine water is due to the release of","hydrogen|nascent oxygen|chloride ions|ozone",1,"Cl₂ + H₂O → HCl + HOCl; HOCl releases nascent oxygen that bleaches.","Descriptive chemistry"),
("Hydrogen sulphide gas turns lead acetate paper","white|black|blue|green",1,"Pb²⁺ + H₂S → black PbS.","Descriptive chemistry"),
("Carbon dioxide turns limewater milky because it forms","CaCl₂|CaCO₃|Ca(OH)₂|CaSO₄",1,"The white precipitate is calcium carbonate.","Descriptive chemistry"),
("Ammonia is manufactured industrially by the","Ostwald process|Haber process|Contact process|Solvay process",1,"N₂ + 3H₂ → 2NH₃ under high pressure with an iron catalyst.","Industrial chemistry"),
("Nitric acid is manufactured by the","Haber process|Ostwald process|Contact process|Dow process",1,"Ostwald: ammonia oxidised over platinum to NO then HNO₃.","Industrial chemistry"),
("Sulphuric acid is manufactured by the","Contact process|Haber process|Ostwald process|Hall process",0,"SO₂ oxidised to SO₃ over V₂O₅ at about 450°C.","Industrial chemistry"),
("Ethene reacts with steam in the presence of H₃PO₄ catalyst to give","ethanol|ethanal|ethanoic acid|ethane",0,"Hydration of ethene → ethanol.","Organic chemistry"),
("Ethanol heated with ethanoic acid and a little H₂SO₄ gives","an ester|an ether|an alkene|a soap",0,"Esterification: ethyl ethanoate + water.","Organic chemistry"),
("The alkaline hydrolysis of fats and oils produces soap and","ethanol|glycerol|glucose|ammonia",1,"Saponification yields soap + glycerol.","Organic chemistry"),
("How many structural isomers has C₄H₁₀?","1|2|3|4",1,"n-butane and 2-methylpropane only.","Organic chemistry"),
("The general molecular formula of the alkanes is","CnH2n|CnH2n+2|CnH2n−2|CnHn",1,"Saturated chain: CnH2n+2.","Organic chemistry"),
("In the addition of HBr to propene, the hydrogen attaches to the carbon with","fewer hydrogens|more hydrogens|any carbon|the middle carbon",1,"Markovnikov's rule: H goes to the carbon already richer in hydrogen.","Organic chemistry"),
("The triple bond present in ethyne makes it suitable for","cooking|welding|painting|fertilising",1,"Ethyne (acetylene) burns very hot — oxy-acetylene welding.","Organic chemistry"),
("Polyethene is formed from ethene by","addition polymerisation|condensation polymerisation|substitution|fermentation",0,"Many ethene monomers add to one another.","Organic chemistry"),
("Benzene undergoes mainly","addition reactions|substitution reactions|combustion only|no reaction",1,"Its delocalised ring prefers substitution, preserving stability.","Organic chemistry"),
("The oxidation of a primary alkanol gives first","an alkanoic acid|an alkanal|a ketone|an ester",1,"Primary alkanol → alkanal (aldehyde) → alkanoic acid.","Organic chemistry"),
("The IUPAC name of CH₃CH(CH₃)CH₂CH₃ is","2-methylbutane|3-methylbutane|butane|dimethylpropane",0,"Longest chain 4; methyl group on carbon 2.","Organic chemistry"),
("The electron configuration of chlorine (Z = 17) is","2,8,7|2,8,8|2,7,8|8,2,7",0,"Shell filling gives 2,8,7.","Atomic structure"),
("The electron configuration of the Fe²⁺ ion (Fe = 2,8,14,2) is","2,8,14|2,8,12,2|2,8,16|2,8,13,2",0,"Atoms lose 4s electrons first: 2,8,14.","Atomic structure"),
("Isotopes of an element have identical chemical properties because they have the same","number of neutrons|number of protons and electrons|mass number|density",1,"Chemistry is decided by electron/proton arrangement.","Atomic structure"),
("Across a period, the atomic radius","increases|decreases|stays constant|fluctuates randomly",1,"Nuclear charge rises and pulls electrons closer.","Periodic table"),
("The elements with the highest first ionisation energy in each period are the","alkali metals|halogens|noble gases|transition metals",2,"Full outer shells make electron removal hardest.","Periodic table"),
("The abnormally high boiling point of water is due to","hydrogen bonding|ionic bonding|covalent size|heavy oxygen",0,"Extensive hydrogen bonds need extra energy to break.","Bonding"),
("Group 1 metals are stored under oil because they","oxidise rapidly in air and react with water|are radioactive|smell strongly|melt easily",0,"Na and K react violently with air and water; oil excludes both.","Descriptive chemistry"),
("Hardness in water is caused mainly by the ions of","Na⁺ and K⁺|Ca²⁺ and Mg²⁺|Fe³⁺ and Al³⁺|NH₄⁺ and H⁺",1,"Calcium and magnesium salts cause hardness.","Descriptive chemistry")
]
