NAME="Christian Religious Studies"
Q=[
("On which day of creation did God make the sun, moon and stars?","Day 1|Day 2|Day 4|Day 6",2,"Day four: the great lights (Genesis 1:14-19).","Creation"),
("Genesis 2:7 says God formed man from","the waters|the dust of the ground|the rib of Adam|clay baked in fire",1,"Dust of the ground plus the breath of life.","Creation"),
("The river that watered Eden and divided into four heads is","Jordan|Pishon|Euphrates|Nile",2,"Four rivers included Pishon, Gihon, Tigris and Euphrates.","Creation"),
("As punishment for the fall, God told the woman","she would toil for food|her pain in childbirth would be greatly multiplied|she would leave the garden|her seed would serve the man's",1,"'I will greatly multiply your pain in childbearing' (Genesis 3:16).","The fall"),
("God rejected Cain's offering because","it was stolen|Cain's heart and offering were not rightly offered|it was too small|it was produce",1,"'Sin is crouching at the door' — wrong disposition.","Cain and Abel"),
("The sign of God's covenant with Noah after the flood was the","circumcision|rainbow|altar of stones|passover blood",1,"The rainbow in the clouds (Genesis 9:13).","Covenants"),
("At Babel, God confused the people's","money|language|worship|architecture",1,"Different languages scattered them (Genesis 11).","Early narratives"),
("God's covenant sign with Abraham was","baptism|circumcision|burning bush|rainbow",1,"Circumcision on the eighth day (Genesis 17).","Covenants"),
("God promised to spare Sodom if ___ righteous people could be found there.","50|20|10|5",2,"Abraham bargained down from fifty to ten (Genesis 18).","Abraham"),
("God commanded Abraham to offer Isaac in the land of","Canaan|Moriah|Egypt|Beersheba",1,"'Take your son... to the land of Moriah' (Genesis 22:2).","Abraham"),
("Jacob's ladder dream occurred at","Bethel|Hebron|Peniel|Shechem",0,"He named the place Bethel, house of God (Genesis 28).","Jacob"),
("Joseph was sold by his brothers to traders on their way to","Egypt|Midian|Syria|Cush",0,"Midianite/Ishmaelite caravans carried him to Egypt (Genesis 37).","Joseph"),
("Pharaoh's dreams that Joseph interpreted foretold","war|seven years of plenty and seven of famine|a plague of locusts|the death of Pharaoh",1,"Seven fat years, then seven lean years (Genesis 41).","Joseph"),
("The cup was found in Benjamin's sack after Joseph","framed him|tested his brothers|mistook him|rewarded him",1,"The silver cup was planted to test their hearts (Genesis 44).","Joseph"),
("The plague that immediately preceded the first Passover was","locusts|darkness|death of the firstborn|hail",2,"The tenth plague struck Egypt's firstborn (Exodus 11-12).","Moses and the Exodus"),
("God gave Moses the Ten Commandments at","Sinai|Horeb|Nebo|Canaan",0,"Mount Sinai, in the third month after the Exodus.","Moses and the Exodus"),
("When Israel made the golden calf, Moses","joined the worship|broke the tablets and burnt the calf|ignored it|exiled Aaron",1,"He shattered the tablets and ground the calf to powder.","Moses and the Exodus"),
("Moses viewed the promised land from","Sinai|Mount Nebo|Hermon|Gilgal",1,"He saw Canaan from Nebo and died there (Deuteronomy 34).","Moses and the Exodus"),
("The walls of Jericho fell after Israel","sapped them|marched round seven days as God commanded|used battering rams|besieged it a year",1,"Seven circuits on the seventh day with trumpets (Joshua 6).","Conquest"),
("Rahab was spared at Jericho because she","bribed the soldiers|hid the spies and tied a scarlet cord in her window|was a queen|knew Joshua",1,"The scarlet cord marked her house (Joshua 2).","Conquest"),
("Israel was defeated at Ai because","the city was too strong|Achan had taken devoted things|it rained heavily|the spies lied",1,"Achan's sin brought the defeat (Joshua 7).","Conquest"),
("Gideon reduced his army to 300 men by testing how the men","fought|drank water|marched|prayed",1,"Those lapping with their hands were chosen (Judges 7).","Judges"),
("Samson lost his strength because","he was wounded|his hair was cut|he ate honey|he left home",1,"Delilah's betrayal led to the shaving of his Nazirite hair (Judges 16).","Judges"),
("Deborah, a prophetess and judge, went to battle with","Barak|Gideon|Samson|Jephthah",0,"Barak accompanied her against Sisera (Judges 4).","Judges"),
("Ruth, the Moabitess, became the great-grandmother of","Saul|David|Solomon|Jeroboam",1,"Ruth → Obed → Jesse → David.","Ruth"),
("Hannah dedicated Samuel to the Lord after","a vow at Shiloh|his illness|a dream|his birth in Jerusalem",0,"Her vow: 'I will give him to the Lord all his life' (1 Samuel 1).","Samuel and the monarchy"),
("Samuel rebuked Saul for sparing King Agag and the best sheep of the","Amalekites|Philistines|Moabites|Ammonites",0,"Partial obedience is disobedience (1 Samuel 15).","Samuel and the monarchy"),
("David spared Saul's life twice, cutting off","his robe's corner|his head|his spear... by the water|his tent",0,"He cut Saul's robe in the cave and took the spear at Hachilah.","David"),
("Nathan confronted David over Bathsheba with the parable of the","lost sheep|rich man and ewe lamb|sower|two sons",1,"The poor man's single lamb stirred David's anger (2 Samuel 12).","David"),
("Absalom rebelled against his father David and died","in battle by the sword|hanging in an oak tree|by poison|in exile",1,"His hair caught him in the great oak (2 Samuel 18).","David"),
("Solomon's judgment over the living child settled the case because the true mother","demanded the child be divided|begged that the child live|was richer|swore an oath",1,"Her compassion revealed motherhood (1 Kings 3).","Solomon"),
("The kingdom split after Solomon because Rehoboam","lowered taxes|vowed to increase the burdens his father laid|built idols|exiled the elders",1,"'My father chastised you with whips... I will with scorpions' (1 Kings 12).","Division of the kingdom"),
("Jeroboam led the ten northern tribes after the division, setting golden calves at","Shiloh and Bethel|Dan and Bethel|Shechem and Penuel|Gilgal and Jericho",1,"Calves at Bethel and Dan (1 Kings 12).","Division of the kingdom"),
("Elijah was fed by ravens at the brook","Kishon|Cherith|Jabbok|Jordan",1,"Ravens brought him bread and meat (1 Kings 17).","Elijah and Elisha"),
("Elijah's contest with the prophets of Baal took place on","Carmel|Sinai|Gerizim|Tabor",0,"Mount Carmel: 'The Lord, he is God' (1 Kings 18).","Elijah and Elisha"),
("Fleeing Jezebel, Elijah heard God not in wind or fire but in a","thunderclap|still small voice|dream|trumpet",1,"The gentle whisper at Horeb (1 Kings 19).","Elijah and Elisha"),
("Elisha asked for a ___ of Elijah's spirit when Elijah departed.","share|double portion|remnant|signet",1,"'Let me inherit a double portion' (2 Kings 2).","Elijah and Elisha"),
("Naaman the Syrian was healed of leprosy by washing","once in Abana|seven times in the Jordan|at Jericho's pool|with wine",1,"Seven dips in the Jordan (2 Kings 5).","Elijah and Elisha"),
("Isaiah's call vision involved a burning coal touching his","heart|lips|eyes|forehead",1,"The seraph purified his unclean lips (Isaiah 6).","Prophets"),
("The prophet who married Gomer as a sign of God's unfailing love was","Amos|Hosea|Micah|Joel",1,"Hosea's marriage symbolised covenant love (Hosea 1-3).","Prophets"),
("Amos, the herdsman of Tekoa, thundered chiefly against","foreign armies|social injustice and oppression of the poor|ritual music|the king of Assyria",1,"'Let justice roll down like waters' (Amos 5).","Prophets"),
("The writing on the wall at Belshazzar's feast read","MENE MENE TEKEL UPHARSIN|ABRACADABRA|ELOI ELOI|MARANATHA",0,"Numbered, weighed, divided (Daniel 5).","Daniel"),
("Daniel's three friends were thrown into the fiery furnace for","theft|refusing to worship Nebuchadnezzar's golden image|treason|witchcraft",1,"Shadrach, Meshach and Abednego (Daniel 3).","Daniel"),
("Daniel survived the lions' den because","the lions were fed|God shut the lions' mouths|he hid|the king relented",1,"'My God sent his angel' (Daniel 6).","Daniel"),
("Jesus' first temptation in the wilderness was to","throw himself down|turn stones into bread|worship Satan|test Scripture",1,"'Command these stones to become bread' (Matthew 4).","Ministry of Jesus"),
("In the parable of the sower, the seed represents","money|the word of God|the kingdom workers|wheat only",1,"'The sower sows the word' (Mark 4).","Parables"),
("The good Samaritan parable answers the question","who is my neighbour?|what must I do to be saved?|when will the kingdom come?|who is the greatest?",0,"'Who is my neighbour?' (Luke 10).","Parables"),
("The parable of the prodigal son chiefly teaches","good farming|God's forgiveness of repentant sinners|inheritance law|brotherly rivalry only",1,"The father runs to welcome the returning son (Luke 15).","Parables"),
("The only miracle recorded in all four gospels is","walking on water|feeding the five thousand|raising Lazarus|healing a leper",1,"The five loaves and two fish (all four gospels).","Ministry of Jesus"),
("Jesus delayed going to Bethany, and Lazarus had been in the tomb ___ days when he arrived.","two|three|four|seven",2,"'He has been dead four days' (John 11).","Ministry of Jesus"),
("At the transfiguration, Jesus spoke with","Moses and Elijah|Abraham and Isaac|Enoch and Elijah|David and Solomon",0,"Moses and Elijah (Matthew 17).","Ministry of Jesus"),
("At the Last Supper, Jesus identified his betrayer as the one","who kissed him|to whom he gave the dipped morsel|who left first|who carried the purse",1,"'It is he to whom I give this morsel' (John 13).","Passion week"),
("In Gethsemane, Jesus prayed that, if possible, ___ pass from him.","the soldiers|this cup|Judas|the cross",1,"'Let this cup pass' (Matthew 26).","Passion week"),
("Peter denied Jesus ___ times before the cock crew.","two|three|four|seven",1,"Three denials (Matthew 26).","Passion week"),
("Jesus was crucified at","Bethany|Golgotha|Emmaus|Gethsemane",1,"'The place of a skull' (John 19).","Passion week"),
("When Jesus died, the temple veil was","stolen|torn in two from top to bottom|painted|burned",1,"Access to God opened (Matthew 27).","Passion week"),
("The first witnesses of the empty tomb were","Peter and John|Mary Magdalene and the other women|the soldiers|the disciples on Emmaus road",1,"The women came first and found the stone rolled away (Matthew 28).","Resurrection"),
("Thomas confessed the risen Christ saying","Hosanna|My Lord and my God|Son of David|Rabboni",1,"'My Lord and my God!' (John 20).","Resurrection"),
("On the road to Emmaus, the disciples recognised Jesus","at the well|in the breaking of bread|at the tomb|during the storm",1,"Their eyes opened at the table (Luke 24).","Resurrection"),
("On the day of Pentecost, Peter's sermon led about ___ people to be baptised.","500|3,000|120|5,000",1,"Three thousand souls (Acts 2).","Acts"),
("The first Christian martyr was","Peter|Stephen|James|Paul",1,"Stephen saw heaven opened as he died (Acts 7).","Acts"),
("Philip explained Isaiah to the Ethiopian official on the road to","Damascus|Gaza|Jericho|Joppa",1,"The Gaza desert road (Acts 8).","Acts"),
("Saul met the risen Christ on the road to","Jerusalem|Damascus|Antioch|Rome",1,"'Why do you persecute me?' (Acts 9).","Acts"),
("Ananias was sent to restore Saul's","speech|sight|limb|memory",1,"Scales fell from his eyes (Acts 9).","Acts"),
("Peter's vision of the sheet taught him that","all animals were clean|Gentiles were not unclean — the gospel is for all|food laws were political|dreams are prophecy",1,"It prepared his visit to Cornelius (Acts 10).","Acts"),
("The Council of Jerusalem (Acts 15) settled the question of","church leadership|whether Gentile converts needed circumcision|the Lord's Supper|missions strategy",1,"Gentiles were not bound by circumcision.","Acts"),
("The fruits of the Spirit in Galatians 5 begin with","faith|love|patience|joy",1,"'But the fruit of the Spirit is love...'","Epistles"),
("'Faith without works is dead' was written by","Paul|James|Peter|John",1,"James 2:26.","Epistles"),
("The great love chapter of the New Testament is","Romans 12|1 Corinthians 13|Ephesians 2|1 John 4",1,"'Love is patient, love is kind' (1 Cor 13).","Epistles"),
("The 'whole armour of God' is described in","Ephesians 6|Romans 13|Hebrews 11|Jude",0,"Helmet of salvation, shield of faith (Ephesians 6).","Epistles"),
("Jesus called himself the Alpha and the Omega, meaning","first and last|two rivers|heaven and earth|day and night",0,"The beginning and the end (Revelation 22).","Revelation")
]
