NAME="Economics"
Q=[
("The fundamental economic problem arises because","resources are unlimited|resources are scarce while wants are unlimited|wants are few|governments print money",1,"Scarcity forces choice and opportunity cost.","Basic concepts"),
("If price rises by 10% and quantity demanded falls by 20%, demand is","perfectly elastic|elastic|inelastic|unitary",1,"PED = 20/10 = 2 > 1: elastic.","Elasticity"),
("For a good with elastic demand, a rise in price causes total revenue to","rise|fall|stay constant|double",1,"Quantity falls proportionally more than the price rises.","Elasticity"),
("Demand for salt is highly inelastic because it is","a luxury|a necessity with many uses|expensive|fashionable",1,"Necessities have inelastic demand.","Elasticity"),
("A rise in the cost of production shifts the supply curve","rightward|leftward|nowhere|downward along itself",1,"Higher costs reduce supply at every price.","Supply"),
("A surplus occurs when price is","below equilibrium|above equilibrium|at equilibrium|falling",1,"Above equilibrium, quantity supplied exceeds quantity demanded.","Price determination"),
("Cross elasticity of demand between two substitute goods is","negative|positive|zero|infinite",1,"Substitutes: demand for one rises when the other's price rises.","Elasticity"),
("For an inferior good, income elasticity of demand is","positive|negative|zero|always above 1",1,"As income rises, demand falls.","Elasticity"),
("Consumer equilibrium occurs where","MUa = MUb|MUa/Pa = MUb/Pb|total utility = 0|price = cost",1,"Equal marginal utility per naira spent.","Utility"),
("Indifference curves cannot intersect because that would imply","identical goods|inconsistent preferences|rising utility|zero income",1,"Intersection gives two different utility levels for one bundle.","Utility"),
("The law of diminishing returns operates only in the","long run|short run with at least one fixed factor|market period|planning horizon only",1,"Short run: some factors are fixed.","Production"),
("As output increases, average fixed cost","rises|falls|stays constant|falls then rises",1,"Fixed cost is spread over more units.","Cost theory"),
("Marginal cost cuts average cost at the","maximum of AC|minimum of AC|zero point|rising part only",1,"MC = AC where AC is at its lowest.","Cost theory"),
("Internal economies of scale cause the long-run average cost to","rise|fall|stay flat|become vertical",1,"Scale economies lower LRAC.","Cost theory"),
("In the long run under perfect competition, firms earn","abnormal profit|normal profit only|losses|monopoly rent",1,"Entry erodes abnormal profit to zero.","Market structures"),
("A monopolist is a","price taker|price maker|perfect competitor|wage setter",1,"Sole seller faces the whole demand curve.","Market structures"),
("Oligopolists' pricing is marked by","independence|interdependence and rigidity|randomness|perfect knowledge only",1,"Each firm watches rivals; prices are sticky (kinked demand).","Market structures"),
("Price discrimination is possible only if markets can be","separated and resale prevented|merged|advertised|subsidised",0,"Separation plus no arbitrage is required.","Market structures"),
("GDP at factor cost equals market price GDP minus","subsidies plus indirect taxes|indirect taxes minus subsidies|depreciation|imports",1,"Factor cost removes net indirect taxes.","National income"),
("Real GDP is obtained by dividing nominal GDP by the","population|price deflator × 100|money supply|export index",1,"Deflating removes price effects.","National income"),
("The expenditure approach measures GDP as","wages + rent + interest + profit|C + I + G + (X − M)|value added|income tax receipts",1,"Spending on final goods.","National income"),
("Per capita income is national income","times population|divided by population|plus subsidies|net of tax",1,"Average income per head.","National income"),
("Demand-pull inflation arises from","rising costs|excess aggregate demand|falling money supply|cheap imports",1,"Too much money chasing goods.","Macroeconomics"),
("Cost-push inflation is triggered by","excess demand|rising production costs|cheap labour|surpluses",1,"Cost increases push prices up.","Macroeconomics"),
("A deflationary gap exists when aggregate demand is","greater than full-employment output|less than full-employment output|equal to output|infinite",1,"Shortfall below capacity output.","Macroeconomics"),
("In MV = PT, V stands for","value|velocity of money circulation|volume of trade|variable cost",1,"How often money changes hands.","Money"),
("A reserve ratio of 20% gives a money multiplier of","2|5|10|20",1,"1/0.2 = 5.","Banking"),
("The central bank's role as 'lender of last resort' means it lends to","commercial banks in distress|private individuals|foreign firms|the stock exchange",0,"It supports banks facing runs.","Banking"),
("Open market operations involve the central bank","selling and buying securities|printing notes|fixing wages|nationalising banks",0,"Trading securities changes money supply.","Banking"),
("Fiscal policy is managed through","money supply and interest rates|government spending and taxation|exchange rates|tariffs only",1,"Budget instruments.","Public finance"),
("A progressive tax is one whose rate","is constant|rises as income rises|falls as income rises|is paid only by firms",1,"Higher incomes pay higher rates.","Public finance"),
("A budget surplus means","revenue exceeds expenditure|expenditure exceeds revenue|both are equal|taxes fall",0,"Government saves the difference.","Public finance"),
("The current account of the balance of payments records","capital flows only|goods, services and transfers|gold movements only|foreign aid only",1,"Trade in goods/services plus income and transfers.","International trade"),
("Balance of trade is the difference between","visible exports and imports|all exports and imports|money in and out|goods and services plus capital",0,"Visible (merchandise) trade only.","International trade"),
("Terms of trade are calculated as","export index ÷ import index × 100|imports ÷ exports|exports − imports|trade balance ÷ GDP",0,"It measures export purchasing power.","International trade"),
("The country with the LOWER opportunity cost in producing a good has","absolute advantage|comparative advantage|no advantage|negative advantage",1,"Comparative advantage is relative opportunity cost.","International trade"),
("Tariffs on imports primarily aim to","punish consumers|protect local industries|raise transport cost|limit exports",1,"They shield domestic producers.","International trade"),
("Under a fixed exchange system, official reduction of the currency value is","revaluation|devaluation|appreciation|floatation",1,"Devaluation lowers the pegged value.","International trade"),
("ECOWAS was established mainly to promote","military alliance|regional economic integration|religion|colonial rule",1,"West African free trade and cooperation.","International economics"),
("The Human Development Index combines life expectancy, education and","military power|income per capita|population size|trade balance",1,"HDI blends health, knowledge and standard of living.","Development"),
("Structural change plus welfare improvement is best described as","economic growth|economic development|inflation|recession",1,"Development is broader than growth.","Development"),
("Unemployment caused by a general fall in aggregate demand is","frictional|cyclical|structural|seasonal",1,"Cyclical (demand-deficient) unemployment.","Labour"),
("Malthus predicted population would outrun","money supply|food supply|cities|technology",1,"Population grows geometrically, food arithmetically.","Population"),
("Optimum population is reached when output per head is","minimum|maximum|zero|constant everywhere",1,"Output per person peaks at optimum.","Population"),
("The historical marketing boards in Nigeria were set up to","buy and export cash crops|print money|build roads|fix exchange rates",0,"They purchased produce from farmers for export.","Nigerian economy"),
("Heavy dependence on crude oil exposes the economy mainly to","price stability|price volatility and Dutch disease|unlimited growth|low wages",1,"Oil price swings destabilise revenue.","Nigerian economy"),
("Privatisation transfers public enterprises to","the military|private ownership|foreign armies|cooperatives only",1,"Sale of state firms to private hands.","Public finance"),
("The Nigerian Enterprises Promotion Decrees promoted","foreign control|indigenous ownership|state monopoly|free imports",1,"Indigenisation transferred business to Nigerians.","Nigerian economy"),
("The money market deals in funds that are","short-term|long-term|foreign only|non-existent",0,"Short-term instruments like treasury bills.","Financial institutions"),
("The stock exchange is primarily a ___ market for securities.","primary|secondary|foreign|retail",1,"Existing shares are traded among investors.","Financial institutions"),
("The precautionary motive for holding money is to","speculate|meet unexpected needs|pay taxes only|earn interest",1,"It buffers against emergencies.","Money")
]
