NAME="English"
Q=[
("Which word does NOT contain the same vowel sound as 'burn'?","heard|fern|heart|hurt",2,"'Heart' has the long vowel sound heard in 'car' while the others share the 'burn' vowel.","Pronunciation"),
("In which word is 'ch' pronounced /k/?","chorus|chin|chirp|rich",0,"'Chorus' takes the /k/ sound as in 'school'.","Pronunciation"),
("Which word contains a silent letter?","doubt|number|rabid|bubble",0,"The 'b' in 'doubt' is silent.","Pronunciation"),
("'The POLICEMAN arrested the thief.' The capitalised stress answers the question:","Who arrested the thief?|Was the thief arrested?|What did the policeman do?|Why was the thief arrested?",0,"Emphatic stress on the doer answers the question 'who did it?'.","Stress and intonation"),
("Which word rhymes with 'bough'?","cough|though|tough|dough",3,"'Dough' shares the 'ow' of 'bough'; the others differ.","Pronunciation"),
("'To bell the cat' means to","provoke a quarrel|take a dangerous risk on behalf of others|refuse a challenge|keep secrets",1,"The idiom comes from the fable of mice putting a bell on the cat: doing the daring task.","Idioms"),
("'A wild-goose chase' is a","furious argument|futile pursuit|hunting expedition|swift victory",1,"It is a hopeless quest that can never be caught.","Idioms"),
("'To fight shy of' something is to","quarrel over it|avoid it|embrace it|postpone it forever",1,"To fight shy of is to keep away from, out of caution.","Idioms"),
("'To eat one's words' is to","retract a statement|speak in riddles|gossip|speak too fast",0,"You publicly admit that what you said was wrong.","Idioms"),
("'At daggers drawn' describes people who are","very tired|openly hostile|closely related|well matched",1,"Ready to fight: open enmity.","Idioms"),
("'To make a clean breast of' something is to","boast about it|confess it fully|clean it up|forget it",1,"Full confession, holding nothing back.","Idioms"),
("'To show the white feather' is to","display cowardice|signal surrender in war|show off|march proudly",0,"A white feather in a gamecock's tail marks a poor fighter, hence cowardice.","Idioms"),
("'To take to one's heels' is to","run away|stand firm|apologise|dance",0,"To flee on foot.","Idioms"),
("'Once in a blue moon' means","nightly|very rarely|monthly|at random",1,"A blue moon is rare; the phrase means very infrequently.","Idioms"),
("'To play second fiddle' is to","take a subordinate role|play music badly|support a rival|lead from behind",0,"From the second violinist of an orchestra: to occupy an inferior position.","Idioms"),
("The judge's 'censure' of the clerk means he","praised him|criticised him|promoted him|forgave him",1,"Censure is strong expressed disapproval.","Lexis in context"),
("The antonym of 'malevolent' is","wicked|benevolent|malicious|crafty",1,"Malevolent means wishing evil; benevolent means wishing good.","Lexis in context"),
("A completely 'innocuous' remark is one that is","insulting|harmless|confusing|hilarious",1,"Innocuous means causing no harm.","Lexis in context"),
("An 'obdurate' man is","stubborn|humble|generous|hasty",0,"Obdurate means unyielding, hardened.","Lexis in context"),
("The antonym of 'urbane' is","polished|awkward|wealthy|urban",1,"Urbane means suave and refined; the opposite is awkward or unsophisticated.","Lexis in context"),
("Neither of the two boys ___ qualified for the final.","is|are|were|have",0,"'Neither' takes a singular verb.","Concord"),
("The quality of the mangoes ___ not good.","is|are|were|have",0,"The subject is 'the quality', which is singular.","Concord"),
("Mathematics ___ the language of the sciences.","is|are|were|have been",0,"Names of disciplines are singular.","Concord"),
("You and I ___ the only witnesses to the accident.","am|is|are|was",2,"Two subjects joined by 'and' take a plural verb.","Concord"),
("Hardly had he arrived ___ the lights went out.","than|when|that|before",1,"'Hardly ... when' is the correct correlating pair.","Concord"),
("No sooner had we set out ___ it began to rain.","than|when|that|then",0,"'No sooner ... than' is the fixed pair.","Concord"),
("If I ___ you, I would tender an apology.","am|was|were|be",2,"The subjunctive 'were' is used in hypothetical statements.","Concord"),
("I'd rather you ___ that decision now.","don't make|didn't make|won't make|not make",1,"'Would rather' is followed by the past subjunctive.","Concord"),
("He has been living in Kano ___ 2010.","for|since|from|before",1,"'Since' is used with a point in time in perfect tenses.","Tense and aspect"),
("By this time next year, I ___ my degree.","will have completed|will complete|complete|would complete",0,"Future perfect marks completion before a stated future time.","Tense and aspect"),
("He told us he ___ that film before.","had seen|has seen|saw|sees",0,"Reported speech of a past event earlier than the reporting verb takes past perfect.","Tense and aspect"),
("Neither the principal nor the teachers ___ present at the assembly.","was|is|were|has been",2,"With 'neither ... nor', the verb agrees with the nearer subject, 'teachers'.","Concord"),
("A pair of trousers ___ lying on the chair.","is|are|were|have been",0,"'Pair' is the headword, so the verb is singular.","Concord"),
("The goods ___ stolen during the night.","was|were|is|has been",1,"'Goods' is a plural-only noun and takes a plural verb.","Concord"),
("One should always be careful about ___ own conduct.","one's|ones|his|their",0,"The possessive of the pronoun 'one' is 'one's'.","Pronouns"),
("Between you and ___, the plan will collapse.","I|me|myself|mine",1,"After a preposition, use the objective pronoun 'me'.","Pronouns"),
("In 'I know that he is honest', the clause 'that he is honest' functions as the","object of the verb 'know'|adverbial of manner|qualifier of 'I'|complement of 'he'",0,"A noun clause following a transitive verb serves as its object.","Clauses"),
("'What he said surprised everyone.' 'What he said' is a ___ clause.","noun|adverbial|adjectival|relative",0,"The whole clause acts as the subject of the sentence, hence a noun clause.","Clauses"),
("The man WHO HELPED ME died last week. The capitalised part is a(n)","adverbial clause|relative clause|noun clause|main clause",1,"'Who helped me' qualifies 'the man', so it is an adjectival (relative) clause.","Clauses"),
("The meeting was called ___ because of the sudden downpour.","off|out|up|over",0,"'Call off' means to cancel.","Phrasal verbs"),
("She takes ___ her mother in both looks and temperament.","after|up|in|over",0,"'Take after' means to resemble a family member.","Phrasal verbs"),
("The chairman could no longer put ___ with the constant insults.","up|off|out|down",0,"'Put up with' means to tolerate.","Phrasal verbs"),
("The suspect was able to get ___ the charges for lack of evidence.","away with|along with|over with|out with",0,"'Get away with' means to escape punishment for.","Phrasal verbs"),
("The teacher talked the boy ___ accepting the transfer.","into|over|with|by",0,"'Talk someone into' means to persuade them to do something.","Phrasal verbs"),
("Which word is correctly spelt?","liason|liaison|liasone|liasson",1,"The correct spelling is 'liaison'.","Spelling"),
("Which word is correctly spelt?","occurence|occurrence|ocurrence|occurrance",1,"'Occurrence' has double 'c', double 'r', ends with '-ence'.","Spelling"),
("Which word is correctly spelt?","harass|harrass|haras|harress",0,"'Harass' has one 'r' and a double 's'.","Spelling"),
("A lawyer's written statement that a document is being filed without conceding its legal effect begins 'without ___'.","precedent|precedence|prejudice|pretense",2,"The fixed legal phrase is 'without prejudice'.","Register"),
("The new engineer is ______ for the fragile plant; he must handle it with care.","on trial|on duty|on parole|on guard",0,"'On trial' means being tested for suitability.","Phrasal usage"),
("The doctor's prescription read 'two tablets ___ die'.","pro tem|per diem|in situ|per annum",1,"'Per diem' means per day.","Register")
]
