NAME="Geography"
Q=[
("On a map with scale 1:50,000, one centimetre represents","0.5 km|5 km|50 km|0.05 km",0,"1 cm × 50,000 cm = 50,000 cm = 0.5 km.","Map reading"),
("On a 1:25,000 map, a distance of 4 cm on paper equals","1 km|10 km|0.25 km|2.5 km",0,"4 × 25,000 cm = 100,000 cm = 1 km.","Map reading"),
("A river falls 100 m over a horizontal distance of 2 km. The gradient is","1:5|1:20|1:2|1:50",1,"100 m rise over 2,000 m = 1 in 20.","Map reading"),
("Contour lines drawn very close together indicate","a gentle slope|a steep slope|a plateau|flat land",1,"Rapid height change over short distance.","Map reading"),
("On a topographic map, V-shaped contour lines pointing UPHILL indicate","a valley|a ridge/spur|a cliff|a lake",1,"Spurs point downhill; Vs in valleys point uphill.","Map reading"),
("A settlement arranged along a road or river is","nucleated|linear|dispersed|isolated",1,"Linear settlements follow a line of communication.","Settlement"),
("The ITCZ brings rain to a region when it","moves poleward past it|stays far away|weakens over the sea|retreats south only",0,"Rain belt follows the overhead sun/ITCZ position.","Climate"),
("The harmattan in Nigeria is caused by","the moist SW monsoon|the dry NE trade wind|sea breezes|the equatorial westerlies",1,"Dry, dusty north-east trades from the Sahara.","Climate"),
("Afternoon thunderstorms with heavy showers typical of southern Nigeria are chiefly","frontal rain|convectional rain|relief rain|cyclonic rain",1,"Intense heating causes convectional rainfall.","Climate"),
("Rainfall totals in Nigeria generally","increase northwards|decrease northwards|are even throughout|peak in the middle belt only",1,"Coastal south gets over 2,000 mm; the far north under 600 mm.","Climate"),
("The vegetation belt lying between the rainforest and the Sudan savanna is the","mangrove swamp|Guinea savanna|Sahel|montane forest",1,"Guinea savanna is the transitional woodland.","Vegetation"),
("Mangrove swamps occur along the coast where","rivers deposit fresh sand|tidal sea water floods the shore|mountains meet the sea|rains fail",1,"Brackish tidal flats host mangroves.","Vegetation"),
("An inselberg is","a volcanic cone|a resistant residual hill rising from a plain|a coral reef|a river delta",1,"An 'island mountain' left by erosion.","Landforms"),
("A mesa is a landform with","a rounded top|a flat top and steep sides|a V-valley|a crater",1,"A flat-topped table land of resistant rock.","Landforms"),
("Karst topography is developed chiefly in","granite|limestone|sandstone|basalt",1,"Carbonation of limestone produces sinkholes and caves.","Landforms"),
("Stalactites and stalagmites are features of","river deltas|limestone caves|sand dunes|glaciers",1,"Dripstone deposits in limestone caverns.","Landforms"),
("A corrie (cirque) is a landform of","river erosion|glacial erosion in a mountain hollow|wind erosion|coastal deposition",1,"Bowl-shaped hollow scoured by valley glacier.","Landforms"),
("Material deposited directly by a glacier is called","alluvium|moraine|loess|talus",1,"Unsorted glacial till dumped as moraine.","Landforms"),
("A crescent-shaped sand dune with its horns pointing downwind is a","barchan|seif|star dune|dome",0,"Barchans migrate across desert floors.","Landforms"),
("Wind erosion that hollows out rock basins and lowers desert floors is","abrasion|deflation|attrition|solution",1,"Deflation blows loose particles away, lowering the surface.","Landforms"),
("In the youthful stage, a river mainly","meanders widely|flows in a steep V-shaped valley|deposits a delta|flows sluggishly",1,"Vertical erosion dominates upstream.","Rivers"),
("An ox-bow lake forms when","a dam is built|a meander neck is cut off|a river floods|springs dry up",1,"The cut-off loop is stranded as a lake.","Rivers"),
("A levee is a natural embankment of","coarse boulders|fine silt along a river's floodplain edge|volcanic ash|sand dunes",1,"Coarser deposits build banks at flood time.","Rivers"),
("Deltas form where rivers meet the sea and the water is","deep and tidal|shallow and fairly calm with fine sediment|rapid and cold|frozen",1,"Shallow shelf + weak currents allow deposition; the Niger delta is arcuate.","Rivers"),
("A sill differs from a dyke in that a sill is","vertical|horizontal (concordant)|curved|sedimentary",1,"Sills intrude parallel to bedding planes.","Landforms"),
("A rift valley forms when","tension cracks the crust and blocks sink|plates collide head-on|rivers erode|volcanoes erupt only",1,"Tensional faulting dropped the central block — East African Rift.","Landforms"),
("Exfoliation, the peeling of rock layers, results from","chemical decay|daily temperature changes|glacial plucking|wave action",1,"Thermal expansion and contraction shed onion skins.","Weathering"),
("The correct soil profile order from top down is","A, O, B, C, R|O, A, B, C, R|B, A, C, O|R, C, B, A",1,"O = organic litter, A = topsoil, B = subsoil, C = parent, R = bedrock.","Soils"),
("The best soil texture for most crops is","clay|sand|loam|gravel",2,"Loam balances drainage and nutrient retention.","Soils"),
("Lateritic soils of the tropics are rich in","calcium|iron and aluminium oxides|sodium|humus",1,"Leaching concentrates Fe and Al oxides.","Soils"),
("Deep gully erosion like that at Agulu (Anambra) is best checked by","planting cover crops and terracing|burning stubble|overgrazing|deep ploughing downhill",0,"Vegetation and terraces bind the soil.","Soil erosion"),
("Contour ploughing reduces erosion because furrows","run downhill and drain fast|follow the contour, slowing run-off|are deeper|are wider",1,"Across-the-slope furrows trap water.","Soil erosion"),
("Population density is obtained by dividing","area by population|population by area|births by deaths|population by houses",1,"People per unit area of land.","Population"),
("Pull factors of migration include","war and famine|jobs, education and better services|drought|land disputes",1,"Attractions draw migrants in.","Population"),
("Major obstacles to accurate census in Nigeria include all EXCEPT","cost|inaccessible terrain|illiteracy|too many trained enumerators",3,"Shortage, not surplus, of enumerators hampers counts.","Population"),
("Rapid urbanisation in Nigerian cities typically causes","ample cheap housing|traffic congestion and unemployment|clean air|cheap land",1,"Cities outgrow services and jobs.","Population"),
("Iron ore deposits are mined at","Jos|Itakpe|Enugu|Sokoto",1,"Itakpe, Kogi State supplies Ajaokuta.","Mineral resources"),
("Coal in Nigeria is mined mainly around","Enugu|Kano|Port Harcourt|Maiduguri",0,"The Enugu coalfield.","Mineral resources"),
("Tin and columbite were traditionally mined on the","Jos Plateau|Mambilla hills|Obudu hills|Zaria plains",0,"Old tin mines of the Jos Plateau.","Mineral resources"),
("Industries locate near raw materials mainly to","reduce transport cost|be near schools|please government|avoid markets",0,"Bulky perishable inputs favour near-source sites.","Industry"),
("The cheapest transport for bulky goods over very long distances is","air|road|water (sea)|rail",2,"Ocean shipping has the lowest cost per tonne-km.","Transport"),
("Shifting cultivation is common in the tropics because","soil regains fertility under fallow|farmers love travel|land is scarce|machines are abundant",0,"Long fallow restores nutrients.","Agriculture"),
("Drip irrigation is valued because it","wastes water|delivers water precisely to plant roots, saving water|floods fields|needs rivers only",1,"Most water-efficient method.","Agriculture"),
("Terracing on steep slopes aims to","speed run-off|reduce soil erosion by slowing water|make roads|plant trees",1,"Steps check slope wash.","Agriculture"),
("Africa's highest mountain is","Kilimanjaro|Kenya|Atlas|Ras Dashen",0,"Kilimanjaro rises about 5,895 m in Tanzania.","Regional geography"),
("The longest river in Africa is the","Congo|Niger|Nile|Zambezi",2,"The Nile flows over 6,600 km.","Regional geography"),
("Africa's largest lake by area is","Tanganyika|Victoria|Chad|Nyasa",1,"Lake Victoria by area; Tanganyika is deepest.","Regional geography"),
("The Niger and Benue rivers meet at","Lokoja|Onitsha|Yenagoa|Baro",0,"The confluence at Lokoja, Kogi State.","Regional geography"),
("Victoria Falls and the Kariba Dam are on the","Niger|Zambezi|Congo|Blue Nile",1,"The Zambezi plunges at Victoria Falls.","Regional geography"),
("The Aswan High Dam, while supplying power and irrigation, caused","more silt downstream in Egypt|the loss of fertile silt that used to flood farms|permanent drought|higher river flow",1,"Silt trapped in Lake Nasser deprived downstream farms.","Regional geography"),
("Rainforest trees commonly show","buttress roots and layered canopy|deep taproots only|leaves lost in winter|thorns only",0,"Tall straight trunks, buttresses, epiphytes.","Vegetation"),
("Desertification in the Sahel is driven by","overgrazing, deforestation and poor farming|only rainfall|sea level|earthquakes",0,"Overuse strips the fragile vegetation cover.","Environmental hazards"),
("Gas flaring in the Niger Delta causes","clean air|acid rain and health hazards|more rainfall|cheaper gas",1,"Flaring wastes gas and pollutes.","Environmental hazards"),
("A warm ocean current such as the Gulf Stream tends to","cool coastal lands|raise coastal temperatures and humidity|cause deserts|lower rainfall",1,"Warm currents warm and moisten coasts.","Oceans"),
("The Benguela current contributes to the Namib desert by","warming the coast|chilling air and suppressing rainfall|bringing storms|raising humidity",1,"Cold air over cold water holds little moisture.","Oceans"),
("The Mediterranean climate is marked by","rain all year|dry summers and wet winters|dry winters and wet summers|monsoons",1,"Summer drought under subtropical highs.","Climate"),
("Atmospheric pressure is measured with a","barometer|anemometer|hygrometer|thermometer",0,"Barometers read air pressure.","Weather instruments"),
("Wind speed is measured by an","anemometer|barometer|wind vane|rain gauge",0,"The anemometer cups spin in the wind.","Weather instruments"),
("The main greenhouse gases include","oxygen and nitrogen|carbon dioxide and methane|argon|helium",1,"CO₂ and CH₄ trap outgoing radiation.","Climate change")
]
