NAME="Government"
Q=[
("The 1914 amalgamation of Nigeria was carried out mainly for","religious reasons|economic and administrative convenience|military conquest|educational expansion",1,"The North's budget deficit was covered by southern revenue.","Nigerian history"),
("The Richards Constitution of 1946 is remembered for introducing","elective principle|regionalism into Nigerian administration|federalism|universal suffrage",1,"It created three regional assemblies.","Nigerian constitutions"),
("The Macpherson Constitution of 1951 introduced","regional assemblies|a central legislature with greater Nigerian participation|self-government|direct military rule",1,"It broadened participation and led to the 1953 crisis.","Nigerian constitutions"),
("Federalism was formally introduced into Nigeria by the","Richards Constitution|Macpherson Constitution|Lyttleton Constitution|Independence Constitution",2,"The 1954 Lyttleton Constitution created the federal structure.","Nigerian constitutions"),
("Under the Independence Constitution of 1960, Nigeria practised","presidential government|parliamentary government|military rule|confederalism",1,"Westminster model with the Queen as head of state.","Nigerian constitutions"),
("Nigeria became a Republic in 1963, making the President","commander-in-chief with executive power|a ceremonial head of state|a prime minister|an colonial officer",1,"Azikiwe became a ceremonial executive-limited president.","Nigerian constitutions"),
("The 1979 Constitution introduced the ___ system of government.","parliamentary|presidential|confederal|military",1,"US-style executive presidency replaced parliamentarism.","Nigerian constitutions"),
("Nigeria currently operates under the","1979 Constitution|1989 Constitution|1999 Constitution|1963 Constitution",2,"The 1999 Constitution (as amended) is in force.","Nigerian constitutions"),
("A key feature of federalism is","one central unit only|a written constitution dividing powers|unwritten conventions|military command",1,"Powers are shared between centre and units.","Political concepts"),
("Features of Nigerian federalism include all EXCEPT","written constitution|division of powers|supremacy of the centre in all matters|state governments",2,"Some powers are exclusive, some concurrent — not all central.","Political concepts"),
("The Northern People's Congress (NPC) was led by","Nnamdi Azikiwe|Ahmadu Bello|Obafemi Awolowo|Herbert Macaulay",1,"The Sardauna of Sokoto led the NPC.","First Republic"),
("The National Council of Nigeria and the Cameroons (NCNC) was led by","Ahmadu Bello|Obafemi Awolowo|Nnamdi Azikiwe|Tafawa Balewa",2,"Azikiwe led the NCNC.","First Republic"),
("The Action Group, formed in 1951, was led by","Obafemi Awolowo|Nnamdi Azikiwe|Ernest Ikoli|Samuel Akisanya",0,"Awolowo founded the AG from the Egbe Omo Oduduwa.","First Republic"),
("The first Nigerian political party, formed in 1923, was the","NCNC|NNDP|AG|NPC",1,"Herbert Macaulay's Nigerian National Democratic Party.","Nationalism"),
("The 1962/1963 census controversy in Nigeria centred on","election rigging|inflated population figures|boundary disputes|currency reform",1,"Regional inflation of figures destroyed census credibility.","First Republic"),
("The January 15, 1966 coup was led by","Yakubu Gowon|Chukwuma Nzeogwu|Johnson Aguiyi-Ironsi|Murtala Mohammed",1,"Major Nzeogwu led the first military coup.","Military era"),
("The Unification Decree No. 34 of 1966, which made Nigeria a unitary state, provoked","southern celebration|northern protests and the July counter-coup|new elections|constitutional reform",1,"It was seen as Igbo domination and triggered the July coup.","Military era"),
("The Nigerian Civil War lasted from","1966 to 1970|1967 to 1970|1967 to 1969|1970 to 1973",1,"Biafra seceded in May 1967; war ended January 1970.","Military era"),
("Post-war reconciliation was pursued through the 3Rs: Reconstruction, Rehabilitation and","Revenge|Reintegration|Reform|Recolonisation",1,"Gowon's 'No victor, no vanquished' policy.","Military era"),
("The 1975 bloodless coup that removed General Gowon was led by","Murtala Mohammed|Olusegun Obasanjo|Ibrahim Babangida|Sani Abacha",0,"Murtala Mohammed led it while Gowon was in Kampala.","Military era"),
("The decision to build a new federal capital at Abuja was taken under","Gowon|Murtala/Obasanjo regime|Shagari|Abacha",1,"The Murtala regime announced Abuja in 1976.","Military era"),
("Nigeria's first executive President under the 1979 Constitution was","Nnamdi Azikiwe|Shehu Shagari|Olusegun Obasanjo|Abubakar Tafawa Balewa",1,"Shagari of the NPN won the 1979 election.","Second Republic"),
("General Buhari took power on","January 15, 1966|December 31, 1983|August 27, 1985|November 17, 1993",1,"The 1983 New Year's Eve coup ended the Second Republic.","Military era"),
("The Structural Adjustment Programme (SAP) was introduced in 1986 under","Buhari|Babangida|Abacha|Abdulsalami",1,"IBB adopted IMF-backed reforms.","Military era"),
("The June 12, 1993 presidential election, annulled by Babangida, was believed won by","Bashir Tofa|M.K.O. Abiola|Ernest Shonekan|Olu Falae",1,"Abiola of the SDP was widely held the winner.","Military era"),
("General Sani Abacha died in June 1998 and was succeeded by","Murtala Mohammed|Abdulsalami Abubakar|Ibrahim Babangida|Yakubu Gowon",1,"Abdulsalami oversaw the 1999 transition.","Military era"),
("Nigeria returned to civilian rule on","October 1, 1960|May 29, 1999|January 1, 1984|June 12, 1993",1,"Obasanjo was sworn in on May 29, 1999.","Fourth Republic"),
("The principles of the rule of law were popularised by","Montesquieu|A.V. Dicey|Jean-Jacques Rousseau|Karl Marx",1,"Dicey's three principles define rule of law.","Political concepts"),
("The doctrine of separation of powers was propounded by","Dicey|Montesquieu|Locke|Hobbes",1,"Montesquieu divided government into three arms.","Political concepts"),
("Checks and balances exist to","concentrate power|prevent abuse by any one arm|abolish the judiciary|end elections",1,"Each arm restrains the others.","Political concepts"),
("Universal adult suffrage in Nigeria grants the vote to citizens aged","16 and above|18 and above|21 and above|25 and above",1,"Voting age is 18.","Electoral systems"),
("A referendum is a direct vote of the electorate to","choose MPs|decide a specific question by yes or no|remove a monarch|tax themselves",1,"Single-issue popular vote.","Electoral systems"),
("A plebiscite differs from a referendum mainly because it usually decides","who governs next|a question of sovereignty or union|tax rates|military budgets",1,"Plebiscites typically settle territorial/political status.","Electoral systems"),
("Government by a few privileged persons is called","democracy|oligarchy|monarchy|gerontocracy",1,"Rule by the few.","Political concepts"),
("Government based on religious authority is a","theocracy|plutocracy|technocracy|democracy",0,"Priestly/religious rule.","Political concepts"),
("Pressure groups differ from political parties because they","contest elections|seek to influence policy without seeking office|control the army|print money",1,"They influence without governing.","Political participation"),
("The principal function of a political party is to","arbitrate disputes|aggregate interests and contest elections|audit accounts|command the police",1,"Parties aggregate interests and seek power.","Political participation"),
("In first-past-the-post, the winner needs","an absolute majority|a simple plurality of votes|two-thirds|a run-off always",1,"Most votes wins, even without majority.","Electoral systems"),
("Under proportional representation, seats are allocated","by district size only|broadly in proportion to votes cast|by seniority|randomly",1,"Vote share maps to seat share.","Electoral systems"),
("Free and fair elections require, among others,","an independent electoral commission|military supervision|state radio only|appointed legislators",0,"Impartial umpires like INEC are essential.","Electoral systems"),
("Power becomes legitimate when","it is seized|the governed accept and recognise it|it is inherited|armies support it",1,"Acceptance confers legitimacy.","Political concepts"),
("A constitution is said to be rigid when amendment","is impossible|needs special elaborate procedures|is by ordinary law|never happens",1,"Rigid constitutions demand special majorities.","Political concepts"),
("In a confederation, sovereignty rests with","the central body|the component states|the judiciary|the military",1,"Member states retain ultimate power.","Political concepts"),
("Devolution differs from federalism because devolved powers","are entrenched and supreme|can be withdrawn by the centre|belong to the army|are hereditary",1,"Devolution is revocable; federal division is entrenched.","Political concepts"),
("Indirect rule succeeded best in Northern Nigeria because","warrant chiefs were strong|it built on the existing emirate system|the British loved the north|there were no rulers there",1,"Emirs already administered through Islamic structures.","Colonial administration"),
("Indirect rule failed largely in the East because the Igbo society was","centralised under kings|acephalous with no paramount chiefs to use|pro-British|urbanised",1,"Warrant chiefs had no traditional legitimacy.","Colonial administration"),
("The British annexed Lagos in 1861/62 primarily to","spread Christianity|suppress the slave trade and secure commerce|find gold|build universities",1,"Treaty with King Dosunmu ended the slave port.","Colonial administration"),
("The Berlin Conference of 1884–85 laid down the principle of","effective occupation|direct democracy|war reparations|free trade in Europe",0,"Colonial claims required effective occupation.","Colonial administration"),
("The Royal Niger Company's territories were sold to the British government in 1900 for","£8,650|£86,500|£865,000|£8,650,000",2,"Goldie sold the RNC charter territories for £865,000.","Colonial administration"),
("The UN Security Council has ___ permanent members with veto power.","5|10|15|7",0,"China, France, Russia, UK, USA.","International relations"),
("Nigeria was suspended from the Commonwealth in 1995 following","a coup|the execution of Ken Saro-Wiwa|an election|an earthquake",1,"Abacha's action drew suspension until 1999.","International relations"),
("The African Union replaced the OAU in 2002 at","Addis Ababa|Durban|Lagos|Cairo",1,"The AU was launched in Durban, South Africa.","International relations")
]
