NAME="History"
Q=[
("The Nok culture is famous for","bronze masks of Ife style|terracotta figures and early iron working|steel bridges|cave paintings only",1,"Nok (c. 500 BC–200 AD) produced terracotta heads and worked iron.","Early Nigerian societies"),
("The bronze and terracotta heads associated with Ile-Ife belong to the","Benin school|Yoruba classical art of Ife|Nok tradition|Igbo-Ukwu only",1,"Ife naturalistic heads are renowned worldwide.","Early Nigerian societies"),
("The British punitive expedition of 1897 looted treasures from","Oyo|Benin|Kano|Sokoto",1,"Benin bronzes were carted away after the invasion.","Early Nigerian societies"),
("In the Oyo empire, the Oyo Mesi functioned mainly as","tax collectors|constitutional checks on the Alaafin|war generals|palace priests",1,"They could compel a bad Alaafin to reject the calabash (abdicate).","Early Nigerian societies"),
("The Oyo empire collapsed partly because","Afonja of Ilorin rebelled with Fulani help|the Alaafin moved to Lagos|rivers flooded|the British invaded Oyo first",0,"Afonja's rebellion plus Fulani pressure broke Oyo.","Early Nigerian societies"),
("Mai Idris Alooma of Kanem-Bornu is remembered for introducing","Christianity|firearms and Islamic law reforms|cotton|the railway",1,"He modernised the army with muskets and appointed qadis.","Early Nigerian societies"),
("The Hausa city-states include","Kano, Katsina and Zaria|Oyo, Ife and Benin|Nupe, Jukun and Igala|Borno, Wadai and Darfur",0,"Bayajidda legend links Daura to the Hausa states.","Early Nigerian societies"),
("Usman dan Fodio's jihad of 1804 led to","the Benin empire|the Sokoto Caliphate|the Oyo empire|Nok culture",1,"The jihad founded the vast Sokoto Caliphate.","Early Nigerian societies"),
("A major cause of the 1804 jihad was","high taxation, corruption and syncretic religion|land scarcity in Lagos|the slave trade alone|colonial taxes",0,"Religious revival fused with grievances against Hausa rulers.","Early Nigerian societies"),
("The Igbo pre-colonial political system was largely","centralised monarchy|acephalous — village groups with elders and age grades|theocratic|military rule",1,"No paramount kings: councils and age grades governed.","Early Nigerian societies"),
("The trans-Atlantic slave trade depopulated West Africa chiefly by","exporting captives across the ocean|settling colonists|building schools|importing cloth",0,"Millions were shipped to the Americas.","Slave trade"),
("British abolition of the slave trade (1807) was driven by","industrial needs, economics and humanitarian pressure|lack of ships|African kings' petitions|weather",0,"Industry wanted raw materials and markets; voices condemned slavery.","Slave trade"),
("Lagos was annexed by Britain in 1861 chiefly to","stop the slave trade and secure trade routes|build a university|grow cocoa|mine gold",0,"King Dosunmu ceded Lagos under treaty pressure.","Colonial rule"),
("The Berlin Conference of 1884–85 established the principle of","effective occupation|indirect rule|free education|war reparations",0,"Powers had to occupy and administer to claim territory.","Colonial rule"),
("The Royal Niger Company under George Goldie held a royal charter from","1861|1886|1900|1914",1,"Chartered in 1886 to administer the lower Niger.","Colonial rule"),
("In 1900 the Royal Niger Company's territories were transferred to the British government for","£865,000|£86,500|£8,650,000|£1,000",0,"The company sold its charter territories.","Colonial rule"),
("The Oil Rivers Protectorate was renamed in 1893 as the","Colony of Lagos|Niger Coast Protectorate|Southern Nigeria|Gold Coast",1,"It became the Niger Coast Protectorate.","Colonial rule"),
("Indirect rule worked well in Northern Nigeria because","the British built schools first|existing emirate institutions were used|the north had no rulers|chiefs were elected",1,"Emirs retained authority under British supervision.","Colonial rule"),
("Indirect rule failed in Igbo country mainly because","the Igbo were absent|no central traditional chiefs existed to mediate|the British refused to appoint anyone|the people welcomed warrant chiefs as kings",1,"Invented warrant chiefs lacked legitimacy.","Colonial rule"),
("The Clifford Constitution of 1922 introduced","regionalism|the elective principle — 4 seats for Lagos and Calabar|federalism|universal suffrage",1,"A limited elective principle began.","Nationalism"),
("Herbert Macaulay's Nigerian National Democratic Party dominated elections in","Calabar|Lagos|Kano|Enugu",1,"NNDP swept Lagos legislative seats in the 1920s.","Nationalism"),
("Nnamdi Azikiwe's West African Pilot popularised the slogan","Blackman's Burden|Show the light and the people will find the way|Africa for Africans at home|Liberty, Equality, Fraternity",1,"The Pilot championed nationalist ideas.","Nationalism"),
("The 1953 self-government motion that sparked the Kano riots was moved by","Ahmadu Bello|Anthony Enahoro|Obafemi Awolowo|Tafawa Balewa",1,"Enahoro moved 'self-government in 1956'.","Nationalism"),
("After the 1953 crisis, the constitution that formalised federalism in 1954 was","Richards|Macpherson|Lyttleton|Oliver Littleton's draft only",2,"Lyttleton's 1954 constitution created the federation.","Nationalism"),
("Eastern and Western regions attained self-government in 1957; the Northern region followed in","1958|1959|1960|1957",1,"The North became self-governing in 1959.","Nationalism"),
("At independence on 1 October 1960, Nigeria's head of government was","the President|the Prime Minister (Abubakar Tafawa Balewa)|the Governor-General alone|the Queen directly",1,"Balewa was federal Prime Minister; Azikiwe became Governor-General.","Independence"),
("Nigeria's first (ceremonial) President in 1963 was","Obafemi Awolowo|Nnamdi Azikiwe|Tafawa Balewa|Ahmadu Bello",1,"Azikiwe became President under the Republican constitution.","First Republic"),
("The 1962 crisis in the Action Group centred on","census fraud|Awolowo's succession and ideology disputes with Akintola|oil revenue|foreign policy",1,"The AG split over leadership and strategy.","First Republic"),
("The 1964 federal election crisis deepened when","NPC and NNDP allies were opposed by UPGA which boycotted parts|all parties agreed|Britain annulled it|the army supported the opposition",0,"UPGA boycotts in some regions worsened tension.","First Republic"),
("The Western Region election crisis of 1965 was nicknamed","Operation Wetie|Wild Goose|Python Dance|Dry Fish",0,"'Wet him with petrol' — arson and mayhem followed rigging.","First Republic"),
("General Ironsi assumed power in January 1966 after","Balewa handed over|the coup leaders' failure produced a vacuum he filled|an election|a court order",1,"With Nzeogwu's coup stalled in the West, the army hierarchy under Ironsi took over.","Military era"),
("General Gowon created 12 states in 1967 mainly to","weaken the east by breaking regions|celebrate independence|build ports|punish the west",0,"Fragmenting the regions countered secession and rallied minorities.","Military era"),
("The Aburi accord (Ghana, 1967) failed to prevent war because","both sides agreed on confederation|the sides interpreted its resolutions differently|Ojukwu wanted money|Gowon resigned",1,"Aburi agreements were read differently in Lagos and Enugu.","Military era"),
("The civil war ended in January 1970 with Gowon declaring","No victor, no vanquished|total revenge|amnesty for Ojukwu only|new borders",0,"The 3Rs policy sought reintegration.","Military era"),
("The 1972/1977 Nigerian Enterprises Promotion Decrees aimed to","attract foreign banks|transfer ownership of businesses to Nigerians|nationalise the press|end farming",1,"Indigenisation advanced Nigerian control.","Economy"),
("Nigeria's oil boom of the early 1970s produced the 1974","Udoji salary awards|Murtala reforms|SAP|Bretton Woods",0,"The Udoji awards raised wages amid plenty.","Economy"),
("General Murtala Mohammed was assassinated in February 1976 during","the Dimka coup attempt|a road accident|the civil war|election riots",0,"Colonel Dimka's abortive coup killed the Head of State.","Military era"),
("Obasanjo's regime handed power to civilians in 1979 to","avoid the 1975 pledge|Murtala's transition programme fulfilled|end sanctions|please Britain",1,"The Murtala/Obasanjo transition culminated in 1979.","Military era"),
("General Babangida came to power in","1983|1985|1993|1979",1,"The August 27, 1985 palace coup removed Buhari.","Military era"),
("The June 12 1993 annulment led to a crisis resolved temporarily by","Ernest Shonekan's Interim National Government|new elections|martial law in Lagos only|Babangida's resignation to Abiola",0,"The ING under Shonekan lasted barely three months.","Military era"),
("General Abacha's rule (1993–98) was marked by","broad press freedom|repression and the return of military absolutism|free elections|regional autonomy",1,"Draconian rule crushed dissent.","Military era"),
("The 1999 transition to civil rule was midwifed by","Abacha himself|Abdulsalami Abubakar's regime|the UN|the Commonwealth",1,"Abdulsalami held elections and handed over May 29, 1999.","Fourth Republic"),
("Marcus Garvey is remembered for advocating","pan-Africanism and 'Back to Africa'|colonial reform in Africa alone|integration|apartheid",0,"His UNIA movement urged Black self-reliance and return.","Pan-Africanism"),
("Kwame Nkrumah led ___ to independence, the first sub-Saharan colony to gain it (1957).","Ghana|Nigeria|Kenya|Senegal",0,"Ghana's independence inspired the continent.","Pan-Africanism"),
("ECOWAS was founded in 1975 with the signing of the Treaty of","Abuja|Lagos|Accra|Lomé",1,"Fifteen states signed in Lagos.","International relations"),
("The OAU (1963) was headquartered in","Lagos|Addis Ababa|Nairobi|Cairo",1,"Addis Ababa hosted the OAU, later the AU.","International relations"),
("Nigeria joined the United Nations in","October 1960|1945|1963|1970",0,"Admitted shortly after independence.","International relations"),
("The immediate cause of the First World War was","the invasion of Poland|the assassination of Archduke Franz Ferdinand at Sarajevo|the Berlin Conference|the Russian revolution",1,"Gavrilo Princip's shot in June 1914 ignited the alliance system.","World history"),
("The Treaty of Versailles (1919) is infamous for","rebuilding Europe generously|the war-guilt clause and reparations on Germany|ending empires|starting the EU",1,"Article 231 humiliated Germany, breeding resentment.","World history"),
("The Second World War in Europe began when Germany invaded","France|Poland|Belgium|Russia",1,"September 1, 1939 — blitzkrieg on Poland.","World history"),
("The atomic bombings that ended the Pacific war hit","Hiroshima and Nagasaki|Tokyo and Osaka|Kyoto and Kobe|Sapporo and Sendai",0,"August 1945 forced Japan's surrender.","World history"),
("The Nuremberg trials established the principle of","amnesty|individual accountability for crimes against humanity|victors' silence|peaceful borders only",1,"Leaders were held personally responsible.","World history"),
("The Industrial Revolution began first in","France|Britain|Germany|USA",1,"Britain industrialised from the late 18th century.","World history"),
("Watt's key improvement powering the Industrial Revolution was the","steam engine|telephone|printing press|cotton gin",0,"James Watt's efficient steam engine drove factories.","World history"),
("Ethiopia kept her independence at the 1896 battle of","Omdurman|Adwa|Isandlwana|Waterloo",1,"Menelik II crushed the Italians at Adwa.","World history"),
("Apartheid in South Africa formally ended with the","1990 reforms only|first all-race democratic elections of 1994|Boer War|UN sanctions of 1977 alone",1,"Mandela's 1994 election closed the era.","World history"),
("The Berlin Wall fell in","1987|1989|1991|1993",1,"November 1989 symbolised the Cold War's end.","World history"),
("NATO (1949) and the Warsaw Pact (1955) embodied","trade blocs|competing military alliances of the Cold War|space programmes|peace treaties",1,"West and East blocs faced off in Europe.","World history"),
("NADECO's role in the 1990s was to","support Abacha|campaign for the actualisation of June 12 and democracy|run football|print money",1,"The National Democratic Coalition rallied pro-democracy forces.","Fourth Republic"),
("The Murtala regime created 19 states in 1976; the current 36-state structure was completed under","Babangida|Abacha|Abdulsalami|Gowon",1,"Abacha's 1996 creation brought the total to 36.","Military era")
]
