NAME="IELTS Academic Practice"
Q=[
("The IELTS band scale runs from","0–5|0–9|1–10|1–12",1,"Bands 0 to 9 in half-band steps.","Test format"),
("Academic Writing Task 1 asks you to","write an opinion essay|describe and summarise visual information|write a letter|translate a passage",1,"Charts, graphs, tables, processes in 150+ words.","Writing"),
("Writing Task 2 requires an essay of at least ___ words.","150|200|250|300",2,"250 words in 40 minutes.","Writing"),
("In Reading, a claim the passage never mentions is marked","False|Not Given|True|Contradictory",1,"'Not Given' means no information either way.","Reading"),
("Skimming a passage means","reading every word|moving fast for the general idea|reading aloud|copying text",1,"Skim for gist; scan for detail.","Reading strategies"),
("Scanning is best for","finding a specific name, date or figure|enjoying the style|improving pronunciation|memorising words",0,"Scanning hunts targeted details.","Reading strategies"),
("In Listening, numbers, dates and plurals commonly cost marks because candidates","write them carelessly|hear them too clearly|never hear them|have perfect spelling",0,"Small details are the classic trap.","Listening"),
("A map-labelling Listening task mainly tests","following directions in a description|essay writing|skimming|speaking speed",0,"You track locations as described.","Listening"),
("Speaking Part 2 gives you a cue card and ___ to speak.","30 seconds|1–2 minutes|5 minutes|10 minutes",1,"You talk 1–2 minutes on the topic.","Speaking"),
("Speaking Part 3 involves","a monologue you memorise|a two-way discussion of abstract issues|reading a passage|writing a summary",1,"Part 3 extends Part 2 into discussion.","Speaking"),
("Linking devices like 'however' and 'consequently' mainly raise your score for","Coherence and Cohesion|Grammar|Pronunciation|Word count",0,"Cohesion is scored explicitly.","Writing criteria"),
("Memorised, rehearsed answers are penalised under","Fluency and Coherence|Task Achievement|Lexical Resource|nothing — they help",0,"Examiners detect memorisation.","Speaking criteria"),
("In True/False/Not Given, a claim CONTRADICTED by the passage is","True|False|Not Given|Half true",1,"Contradiction = False; silence = Not Given.","Reading"),
("General Training Reading differs from Academic mainly by using","harder science texts|everyday, workplace and general materials|no passages|only advertisements",1,"GT sources are practical.","Test format"),
("The Listening test plays each recording","twice|once only|three times|until you finish",1,"Each recording is played once only.","Listening"),
("Answers must reach the answer sheet during Listening time; notes on the question paper","must be erased|are not marked|must be rewritten|count double",1,"Only the answer sheet is marked.","Listening"),
("Spelling in Listening and Reading must be","perfectly correct|nearly correct|phonetic|optional",0,"Incorrect spelling loses the mark.","Listening"),
("In Academic Writing Task 1, you must NOT","describe trends|give a personal opinion on the data|compare categories|select key features",1,"Task 1 reports, never opines.","Writing"),
("A formal Task 2 essay avoids","clear paragraphs|contractions like don't and can't|linking words|a clear position",1,"Formal register bans contractions.","Writing"),
("The Task 2 introduction should","copy the prompt verbatim|paraphrase the question and state your position|tell a personal story|list synonyms",1,"Paraphrase plus position sets up the essay.","Writing"),
("Writing far beyond the word limit is","penalised per extra word|allowed if quality stays high|not read after 290 words|an automatic band cut",1,"No fixed rule against length, but more words risk more errors.","Writing"),
("Reading passages get progressively","easier|harder|shorter|faster",1,"Passage 3 is typically the hardest.","Reading"),
("Matching headings mainly tests your grasp of","paragraph main ideas|exact sentences|grammar|spelling",0,"Headings summarise paragraphs.","Reading"),
("Summary completion requires words that fit both ___ and grammar, taken from the passage.","colour|meaning|length|accent",1,"Meaning plus grammatical fit from the text.","Reading"),
("The Reading test overall time is","20 minutes per passage at will|60 minutes total|30 minutes total|90 minutes",1,"60 minutes for three passages.","Test format"),
("Speaking is assessed on Fluency, Lexical Resource, Grammatical Range and","Volume|Pronunciation|Speed|Posture",1,"Pronunciation is the fourth criterion.","Speaking criteria"),
("Long silent pauses during Speaking mostly hurt","Fluency and Coherence|Vocabulary|Task Response|Handwriting",0,"Fluency penalises hesitation.","Speaking criteria"),
("Brief self-correction in Speaking is","always fatal|fine when natural|penalised to band 0|impossible",1,"Natural speech includes small corrections.","Speaking criteria"),
("Idiomatic language raises your score when","memorised in lists|used accurately in context|translated literally|forced everywhere",1,"Accurate, natural idioms lift Lexical Resource.","Speaking criteria"),
("The Listening section has ___ parts.","2|3|4|5",2,"Four sections, forty items.","Test format"),
("The Reading test has ___ questions.","30|40|50|60",1,"Forty questions overall.","Test format"),
("In the Writing band, Task 2 carries roughly ___ of the weight.","half|two thirds|one third|exactly equal",1,"Task 2 counts about twice Task 1.","Test format"),
("Which best paraphrases: 'The graph shows a sharp rise in car ownership'?","Cars went up very high lots.|The chart illustrates a steep increase in car ownership.|The graph is showing sharp rise cars.|Car ownership graph sharp rising.",1,"Academic verbs plus correct structure.","Writing"),
("Which is the best overview sentence for a line graph?","Then it went up and down.|Overall, the figures for both cities trended upward over the period.|In 2010 the line was at 20 and later 25 in 2012 and after that 30.|Firstly, secondly, thirdly.",1,"An overview states the main trend.","Writing"),
("Describing 20% as 'a fifth' shows","weak maths|good lexical range|a spelling error|band 4 behaviour",1,"Range of fraction forms is rewarded.","Writing"),
("'Surged' and 'plummeted' are precise verbs for","rising and falling sharply|slow change|stability|repetition",0,"They describe steep movement.","Writing"),
("Which reply fits: 'Where are you from?'","I come from Lagos, a busy coastal city in Nigeria.|Lagos. Lagos. My city Lagos.|From... from place.|I am not telling you.",0,"Natural expansion with detail scores well.","Speaking"),
("In Part 3, the best answers","list bullet points|explore reasons, examples and implications|answer yes or no only|repeat the question",1,"Part 3 rewards developed argument.","Speaking"),
("Which shows grammatical range?","I went. I see. I will go.|Having lived abroad, I have grown used to different cuisines.|I go shop and I go home and I go sleep.|It was good, it was nice, it was fine.",1,"Complex structures demonstrate range.","Grammar"),
("Choose the correct sentence.","There is many reasons.|There are many reasons for this trend.|Their is many reasons.|There many reasons are.",1,"Plural subject needs 'are'.","Grammar"),
("Choose correctly: 'The number of people ___ increasing.'","are|is|were|have",1,"'The number of' is singular.","Grammar"),
("Choose the articles: 'He is ___ engineer at ___ university.'","an / a|a / an|an / an|a / a",0,"'Engineer' takes an; 'university' takes a.","Grammar"),
("Choose: 'By 2020, she ___ here for ten years.'","works|had worked|is working|work",1,"Past perfect for duration before a past point.","Grammar"),
("Choose: 'Neither the manager nor the staff ___ ready.'","was|were|is|has",1,"Agreement follows the nearer plural subject.","Grammar"),
("A body-paragraph topic sentence should","ask a question|state the paragraph's main point|quote the examiner|apologise",1,"Each paragraph opens with its point.","Writing"),
("Which linking phrase signals contrast?","In addition|On the other hand|For instance|To conclude",1,"'On the other hand' contrasts.","Cohesion"),
("Which phrase signals an example?","However|For example|Consequently|Conversely",1,"'For example' introduces an illustration.","Cohesion"),
("The best Task 2 conclusion","repeats the introduction verbatim|restates the position in fresh wording|adds a brand-new argument|ends with a question to the reader",1,"Conclusions restate, not restart.","Writing"),
("If you hear 'to rent' as the answer, you write","to rent|to renting|renting|rent to",0,"Write exactly the words heard that fit the gap.","Listening"),
("Before writing Task 1, first","count all words|analyse axes, units and key features|write the conclusion first|copy the question",1,"Understanding the visual drives Task Achievement.","Writing")
]