NAME="Literature"
Q=[
("A Shakespearean sonnet consists of","12 lines|14 lines|16 lines|10 lines",1,"Three quatrains and a closing couplet.","Poetry"),
("A Petrarchan sonnet is structured as","three quatrains and a couplet|an octave and a sestet|two tercets|free verse",1,"Octave (abbaabba) plus sestet.","Poetry"),
("Blank verse is","rhymed iambic pentameter|unrhymed iambic pentameter|free verse|quatrain verse",1,"Regular meter but no rhyme.","Poetry"),
("Free verse is characterised by","strict rhyme|no regular metre or rhyme|fourteen lines|heroic couplets",1,"It rejects fixed patterns.","Poetry"),
("A ballad is a ___ poem meant to be sung.","narrative|lyric of mourning|satirical|dramatic monologue",0,"A ballad tells a story, often in song form.","Poetry"),
("An ode is a lyric poem","mourning the dead|addressed to a person, object or occasion|telling a war story|mocking a king",1,"Odes celebrate or address their subject.","Poetry"),
("An elegy is a poem of","praise|lamentation for the dead|war|love",1,"It mourns the dead.","Poetry"),
("An epic poem is","short and personal|a long narrative about heroic deeds|a funny song|a two-line epigram",1,"Epics recount heroic action at length.","Poetry"),
("'Living death' is an example of","oxymoron|hyperbole|irony|litotes",0,"Contradictory terms placed together.","Figures of speech"),
("Referring to workers as 'hands' is","metonymy|synecdoche|irony|euphemism",1,"A part standing for the whole.","Figures of speech"),
("Referring to the monarchy as 'the Crown' is","synecdoche|metonymy|oxymoron|pun",1,"An associated term stands for the thing.","Figures of speech"),
("'She broke the record and his heart' is an example of","zeugma|hyperbole|paradox|simile",0,"One verb governs two objects with different senses.","Figures of speech"),
("'Not bad at all' as praise is","litotes|hyperbole|irony|paradox",0,"Understatement by negation.","Figures of speech"),
("Saying someone 'passed away' instead of 'died' is","euphemism|sarcasm|paradox|pun",0,"A gentler substitute for a harsh term.","Figures of speech"),
("Addressing an absent person or an abstraction directly is","apostrophe|assonance|antithesis|anaphora",0,"'O Death, where is thy sting?'","Figures of speech"),
("'Buzz', 'hiss' and 'crackle' are examples of","onomatopoeia|alliteration|assonance|oxymoron",0,"Words that imitate sounds.","Figures of speech"),
("'I have told you a million times' is","hyperbole|litotes|irony|zeugma",0,"Deliberate exaggeration.","Figures of speech"),
("Sarcasm differs from plain irony because it","praises|carries a bitter, cutting intent|is accidental|needs rhyme",1,"Sarcasm is irony with sting.","Figures of speech"),
("Dramatic irony occurs when","the audience knows what the character does not|two actors argue|a character lies|the play is comic",0,"The gap between audience and character knowledge.","Drama"),
("A soliloquy is delivered","to another character|by a character alone, revealing inner thoughts|by the narrator|off stage",1,"Alone on stage, thinking aloud.","Drama"),
("An aside is","a long speech|a brief remark heard by audience/one character but not others|a stage direction|the final act",1,"A whispered comment bypassing others onstage.","Drama"),
("The tragic flaw of a protagonist is called","hubris|hamartia|catharsis|peripeteia",1,"Hamartia is the error or flaw causing the fall.","Drama"),
("The purging of pity and fear in an audience, per Aristotle, is","catharsis|pathos|bathos|mimesis",0,"Tragedy cleanses the emotions.","Drama"),
("Hubris in a tragic hero is","poverty|overweening pride that offends the gods|cowardice|silence",1,"Excessive pride precedes the fall.","Drama"),
("The denouement is the","opening scene|final unravelling of the plot|comic relief|climax fight",1,"The knot of the story is untied.","Drama"),
("Background information a reader needs at the start is called","exposition|denouement|peripeteia|anagnorisis",0,"The setup of the story.","Drama"),
("The character who opposes the protagonist is the","protagonist|antagonist|foil|narrator",1,"The opposing force.","Drama"),
("A flat character is one who","changes greatly|shows one or two traits without complexity|narrates|dies early",1,"Simple and unchanging.","Literary terms"),
("A character used to highlight the protagonist's qualities by contrast is a","foil|foil 'double'|chorus|villain only",0,"The foil contrasts to reveal traits.","Literary terms"),
("Hints of events to come in a narrative constitute","flashback|foreshadowing|exposition|denouement",1,"Planted clues about the future.","Literary terms"),
("A flashback","predicts the future|presents an earlier event out of sequence|ends the story|is spoken by the chorus",1,"It interrupts chronology with the past.","Literary terms"),
("The central idea explored in a work is its","subject matter|theme|plot|diction",1,"Theme is the underlying idea.","Literary terms"),
("A story told by a character using 'I' has a ___ narrator.","first-person|third-person|omniscient|reliable",0,"First-person point of view.","Literary terms"),
("An omniscient narrator","knows only one character|knows the thoughts of all characters|is absent|speaks only in rhyme",1,"God-like knowledge of the story.","Literary terms"),
("The time and place of a narrative form its","plot|setting|theme|style",1,"Setting situates the story.","Literary terms"),
("Satire aims to","entertain only|ridicule vice or folly to correct it|praise leaders|teach grammar",1,"Satire uses humour to reform.","Literary terms"),
("A parody is","an original hymn|an imitation for comic effect|a tragedy|a translation",1,"Comic mimicry of a work or style.","Literary terms"),
("Pathos appeals to the audience's","fear|pity and sorrow|greed|humour",1,"It stirs tender emotion.","Literary terms"),
("Bathos is a","sudden rise from trivial to sublime|sudden drop from the sublime to the trivial|long speech|rhyme scheme",1,"Anticlimax: the grand collapses into the petty.","Literary terms"),
("A pun plays on","two meanings of a word|two characters|two rhymes|two acts",0,"Double sense for wit.","Literary terms"),
("In 'Othello', Iago's stated grievance is that","Othello stole his money|Cassio was promoted lieutenant over him|Desdemona insulted him|he was demoted to sergeant",1,"Iago resents the 'one Michael Cassio' promotion.","Othello"),
("Othello's tragic flaw is chiefly","jealousy|generosity|patience|silence",0,"'The green-eyed monster' destroys him.","Othello"),
("Desdemona dies","by poison|strangled by Othello|in a shipwreck|by her own hand",1,"Othello smothers/strangles her believing her false.","Othello"),
("In 'Things Fall Apart', Okonkwo's father Unoka was","a great warrior|lazy and debt-ridden|a wealthy trader|a priest",1,"Unoka's failure drives Okonkwo's obsession.","Things Fall Apart"),
("Okonkwo is exiled from Umuofia for","killing a clansman accidentally at a funeral|stealing a goat|insulting the oracle|refusing a duel",0,"His gun accidentally killed Ezeudu's son.","Things Fall Apart"),
("Ikemefuna's death is tragic because","Okonkwo struck the fatal blow despite warning|the clan stoned him|he died of sickness|he fled the clan",0,"Okonkwo cut him down to not seem weak.","Things Fall Apart"),
("'Things Fall Apart' closes with the District Commissioner","adopting Okonkwo's son|planning a book paragraph on the affair|burning the village|fleeing",1,"He reduces Okonkwo's tragedy to a paragraph.","Things Fall Apart"),
("In 'The Lion and the Jewel', Lakunle is","the Bale|a westernised schoolteacher|a hunter|Sidi's father",1,"He courts Sidi with bookish modernity.","The Lion and the Jewel"),
("Sidi is called 'the jewel' because she","owns jewels|is the village beauty|sings|is Baroka's daughter",1,"Her beauty is Ilujinle's pride.","The Lion and the Jewel"),
("Baroka defeats Lakunle by","buying Sidi|cleverly playing on Sidi's vanity about his lost virility|force|courting her father",1,"The sly Bale tricks and wins Sidi.","The Lion and the Jewel"),
("The narrator of 'Purple Hibiscus' is","Kambili|Eugene|Aunty Ifeoma|Jaja's sister",0,"Kambili Achike tells the story.","Purple Hibiscus"),
("Papa Eugene in 'Purple Hibiscus' is portrayed as","a gentle democrat|a fanatically religious and abusive father|a poor farmer|a pastor of a small church",1,"His piety masks domestic tyranny.","Purple Hibiscus")
]
