NAME="Physics"
Q=[
("A body starts from rest and accelerates uniformly at 4 m/s². Find its velocity after covering 50 m.","20 m/s|16 m/s|25 m/s|12.5 m/s",0,"v² = u² + 2as = 0 + 2(4)(50) = 400 → v = 20.","Motion"),
("The range of a projectile is maximum when the angle of projection is","30°|45°|60°|90°",1,"R = u²sin2θ/g is maximum when sin2θ = 1, i.e. θ = 45°.","Motion"),
("A man in a lift accelerating upward at a m/s² experiences an apparent weight of","m(g−a)|m(g+a)|mg|zero",1,"R − mg = ma → R = m(g + a).","Newton's laws"),
("The escape velocity from the Earth's surface is approximately","7.9 km/s|11.2 km/s|5.0 km/s|16.7 km/s",1,"About 11.2 km/s is needed to escape Earth's gravity.","Gravitation"),
("The acceleration due to gravity at height h above the Earth's surface (h << R) is approximately","g(1 − 2h/R)|g(1 − h/R)|g(1 + 2h/R)|g(1 + h/R)",0,"gh = GM/(R+h)² ≈ g(1 − 2h/R) for small h.","Gravitation"),
("A geostationary satellite has a period of","12 hours|24 hours|365 days|one lunar month",1,"It appears fixed, so it rotates with Earth's 24-hour period.","Gravitation"),
("The Young modulus of a material is the ratio of","stress to strain|force to extension|mass to weight|work to time",0,"Young modulus = tensile stress/tensile strain, in N/m².","Elasticity"),
("A spring of natural length 20 cm extends by 4 cm under a load of 2 N. Find the force constant.","0.5 N/cm|8 N/cm|0.5 N/m|50 N/m",0,"k = F/e = 2/4 = 0.5 N/cm.","Elasticity"),
("The work done in stretching a spring of constant k to extension e is","ke|½ke|½ke²|ke²",2,"Work = average force × extension = ½ke².","Energy"),
("A machine of efficiency 80% receives 500 J of input energy. The useful output is","500 J|400 J|625 J|80 J",1,"Output = 0.8 × 500 = 400 J.","Energy"),
("Find the heat needed to raise 2 kg of water by 5°C. (c = 4200 J/kgK)","42,000 J|4,200 J|8,400 J|21,000 J",0,"Q = mcΔθ = 2 × 4200 × 5 = 42,000 J.","Heat"),
("Calculate the heat required to melt 0.5 kg of ice at 0°C. (L = 3.34 × 10⁵ J/kg)","1.67 × 10⁵ J|3.34 × 10⁵ J|8.35 × 10⁴ J|6.68 × 10⁵ J",0,"Q = mL = 0.5 × 3.34 × 10⁵ = 1.67 × 10⁵ J.","Heat"),
("At constant pressure, the volume of a fixed mass of gas is directly proportional to its absolute temperature. This is","Boyle's law|Charles' law|Gay-Lussac's law|Dalton's law",1,"That is Charles' law.","Gas laws"),
("A gas occupies 300 cm³ at 100 kPa. Find its volume at 150 kPa, temperature constant.","450 cm³|200 cm³|150 cm³|250 cm³",1,"Boyle: V₂ = 100×300/150 = 200 cm³.","Gas laws"),
("Heat transfer that requires no material medium is","conduction|convection|radiation|evaporation",2,"Radiation travels through a vacuum.","Heat"),
("A wave has frequency 50 Hz and wavelength 4 m. Find its speed.","200 m/s|12.5 m/s|54 m/s|100 m/s",0,"v = fλ = 50 × 4 = 200.","Waves"),
("The period of a wave of frequency 50 Hz is","0.02 s|0.2 s|50 s|2 s",0,"T = 1/f = 0.02 s.","Waves"),
("The fundamental wavelength of a sound in an OPEN pipe of length L is","L|2L|4L|L/2",1,"Open pipe fundamental: λ = 2L.","Waves"),
("In a CLOSED pipe, the frequency of the third overtone is","3f|5f|7f|2f",2,"Closed pipes give odd harmonics: f, 3f, 5f, 7f; the third overtone is 7f.","Waves"),
("The apparent frequency of a source moving towards a listener is","lower than the source frequency|higher than the source frequency|equal|zero",1,"Doppler effect: approaching source raises the apparent pitch.","Waves"),
("The critical angle C for a medium of refractive index n is given by","sin C = n|sin C = 1/n|tan C = 1/n|cos C = n",1,"At critical angle, sin C = 1/n.","Optics"),
("An object is placed 30 cm from a converging lens of focal length 10 cm. Find the image distance.","15 cm|−15 cm|7.5 cm|30 cm",0,"1/f = 1/u + 1/v → 1/10 − 1/30 = 1/30, v = 15 cm.","Optics"),
("The magnification of the image in question 22 is","2|0.5|3|1.5",1,"m = v/u = 15/30 = 0.5.","Optics"),
("In the dispersion of white light by a prism, the colour deviated MOST is","red|violet|green|yellow",1,"Violet has the shortest wavelength and deviates most.","Optics"),
("Two sources producing a stable interference pattern must be","incoherent|coherent|in phase always|unpolarised",1,"Interference requires coherent sources with a constant phase difference.","Optics"),
("The spreading of waves around the edges of an obstacle is","refraction|diffraction|reflection|polarisation",1,"Diffraction is the bending and spreading of waves at edges.","Waves"),
("In the photoelectric effect, no electrons are emitted when the incident light frequency is","above the threshold|below the threshold|exactly at threshold|any frequency",1,"Below the threshold frequency the photon energy is insufficient, no matter the intensity.","Quantum physics"),
("The maximum kinetic energy of photoelectrons equals","hf|Φ|hf − Φ|hf + Φ",2,"KE(max) = hf − Φ where Φ is the work function.","Quantum physics"),
("The equation E = mc² expresses the equivalence of","mass and velocity|energy and mass|charge and mass|force and energy",1,"Mass-energy equivalence from Einstein's special relativity.","Nuclear physics"),
("An alpha particle is identical with","a proton|a helium nucleus|an electron|a hydrogen atom",1,"An alpha particle is a helium nucleus: 2 protons + 2 neutrons.","Nuclear physics"),
("Gamma rays are","electrons|electromagnetic waves|helium nuclei|neutrons",1,"Gamma rays are high-energy electromagnetic radiation.","Nuclear physics"),
("A radioactive isotope has a half-life of 8 hours. The time taken for the activity to fall to 1/16 of its original value is","16 h|24 h|32 h|40 h",2,"1/16 = four half-lives = 32 hours.","Nuclear physics"),
("Commercial nuclear reactors obtain energy from","nuclear fusion|nuclear fission of U-235|chemical combustion|alpha decay",1,"Reactors use controlled fission of uranium-235.","Nuclear physics"),
("If 12 C of charge passes a point in 4 s, the current is","3 A|48 A|0.33 A|8 A",0,"I = Q/t = 12/4 = 3 A.","Current electricity"),
("Resistors of 3 Ω and 6 Ω are connected in parallel. The equivalent resistance is","2 Ω|9 Ω|18 Ω|4.5 Ω",0,"1/R = 1/3 + 1/6 = 1/2 → R = 2 Ω.","Current electricity"),
("The resistivity ρ of a material of resistance R, length L and cross-sectional area A is","RL/A|RA/L|R/A L|R L A",0,"R = ρL/A → ρ = RA/L.","Current electricity"),
("A cell of emf 12 V and internal resistance 0.5 Ω drives a current of 2 A. The external resistance is","5.5 Ω|6 Ω|6.5 Ω|5 Ω",0,"E = I(R + r) → 12 = 2(R + 0.5) → R = 5.5 Ω.","Current electricity"),
("Find the power dissipated in a 3 Ω resistor carrying 2 A.","12 W|6 W|1.5 W|24 W",0,"P = I²R = 4 × 3 = 12 W.","Current electricity"),
("The commercial unit of electrical energy is the","watt|kilowatt-hour|joule|volt",1,"Electricity is sold in kilowatt-hours (units).","Current electricity"),
("The balance condition of a Wheatstone bridge requires","P = Q|R = S|P/Q = R/S|P R = Q S",2,"At balance, the ratios of the arms are equal: P/Q = R/S.","Current electricity"),
("The force on a current-carrying conductor in a magnetic field is","BIL sinθ|BIL cosθ|B/IL|B I / L",0,"F = BIL sinθ, maximum when the conductor is perpendicular to the field.","Electromagnetism"),
("Fleming's left-hand rule is used to find the direction of force on a","moving charge in an electric field|current-carrying conductor in a magnetic field|induced current|a falling magnet",1,"It relates field, current and force (motor effect).","Electromagnetism"),
("The direction of an induced current is such as to oppose the change producing it. This is","Faraday's law|Lenz's law|Ohm's law|Ampere's law",1,"Lenz's law: induced effects oppose their cause.","Electromagnetism"),
("In an ideal step-up transformer, if the voltage rises 10 times, the current","rises 10 times|falls to one tenth|stays constant|doubles",1,"Power is conserved: voltage up, current down.","Electromagnetism"),
("The part of a d.c. generator that keeps the current flowing one way is the","slip ring|commutator|brush|armature",1,"The split-ring commutator reverses connections each half turn.","Electromagnetism"),
("Cathode rays are streams of","protons|electrons|neutrons|X-rays",1,"Cathode rays are fast-moving electrons.","Atomic physics"),
("X-rays are produced when","slow neutrons hit a target|fast electrons strike a metal target|alpha particles hit paper|light strikes a photocell",1,"Sudden deceleration of fast electrons in a metal target emits X-rays.","Atomic physics"),
("Which logic gate is universal, being able to build all others?","AND|OR|NOT|NAND",3,"NAND (and NOR) can combine to form every other gate.","Electronics"),
("Doping pure silicon with a pentavalent impurity produces","p-type|n-type|intrinsic|insulating",1,"Five valence electrons leave a free electron: n-type.","Electronics"),
("A transformer is rated 240 V to 12 V. If the primary has 2000 turns, the secondary has","100 turns|200 turns|40,000 turns|500 turns",0,"Ns/Np = Vs/Vp → Ns = 2000 × 12/240 = 100.","Electromagnetism")
]
