NAME="SAT Reading & Writing"
Q=[
("Choose the transition: 'The forecast promised sunshine; ___, we packed umbrellas.'","therefore|however|moreover|likewise",1,"Contrast between promise and action.","Transitions"),
("'The committee ___ divided over the new proposal.' Choose the correct verb.","were|was|are|have been",1,"A single collective committee takes 'was'.","Agreement"),
("'Each of the candidates ___ required to submit transcripts.' Choose correctly.","are|is|were|have been",1,"'Each' is singular.","Agreement"),
("'The novels of Chimamanda Adichie, who ___ from Nigeria, have won awards.'","is coming|comes|come|have come",1,"'Who' refers to one author: singular 'comes'.","Agreement"),
("Choose the clearest pronoun: 'When Sara met with Anna, ___ gave her the report.'","she|they|Sara|it",2,"Naming the subject removes the ambiguity.","Pronoun clarity"),
("'Neither the manager nor the staff ___ aware of the change.'","was|were|is|has been",1,"Verb agrees with nearer plural 'staff'.","Agreement"),
("Which sentence is parallel?","She likes hiking, to swim, and bikes.|She likes hiking, swimming, and biking.|She likes to hike, swimming, and biking.|She likes hiking, swim, and to bike.",1,"All gerunds match.","Parallelism"),
("'Running down the street, the bus was missed by the boy.' This sentence has","a comma splice|a dangling modifier|a run-on|correct structure",1,"The bus was not running; the modifier dangles.","Modifiers"),
("'After reading the novel, I found the film ___.' Choose the correct word.","dissatisfied|unsatisfied|satisfying|less satisfactory",1,"The film left expectations unmet: unsatisfied... actually 'disappointing'. Best here: 'unsatisfying'.","Diction"),
("Which is correct?","The team celebrated it's victory.|The team celebrated its victory.|The team celebrated their's victory.|The teams celebrated its victory.",1,"Possessive 'its' has no apostrophe.","Punctuation"),
("'The seminar covered three topics: theory, method, and ethics.' The colon is correct because","it introduces a list after a complete clause|it separates two clauses|it marks dialogue|colons always fit lists",0,"A colon follows an independent clause.","Punctuation"),
("'She was exhausted; she still finished the report.' The semicolon","splices two clauses wrongly|correctly joins two independent clauses|should be a comma|needs a colon",1,"Semicolons join independent clauses.","Punctuation"),
("Which phrase is redundant?","absolutely essential|very essential|essential|most essential",0,"Essential is absolute by definition.","Conciseness"),
("Which sentence is most concise?","Due to the fact that it rained, we stayed home.|Because it rained, we stayed home.|Owing to the rain, we remained at home.|In view of the rain, we chose to stay home.",1,"'Because' is shortest and clearest.","Conciseness"),
("'Fewer' is correctly used with","countable nouns|uncountable nouns|abstract nouns only|singular nouns",0,"Fewer books, less water.","Diction"),
("Choose correctly: 'The new policy will ___ every department.'","affect|effect|effectuate|affection",0,"Verb 'affect' = influence.","Diction"),
("Choose correctly: 'The ___ of the experiment was surprising.'","affect|effect|affective|affected",1,"Noun 'effect' = result.","Diction"),
("Choose: 'She ___ the book on the table.'","lay|laid|lain|lie",1,"Past tense of transitive 'lay' is 'laid'.","Diction"),
("Choose: 'He ___ down for an hour.'","lay|laid|lied|lain",0,"Past of intransitive 'lie' is 'lay'.","Diction"),
("The head of a school is its","principal|principle|principals|principality",0,"'Principal' = the head.","Diction"),
("A firm's ___ are its standards.","principles|principals|principal|principle",0,"'Principles' = moral rules.","Diction"),
("A word completing praise is a","complement|compliment|compilation|complementation",1,"A 'compliment' is praise.","Diction"),
("Parked cars must be ___; writing paper is ___.","stationary / stationery|stationery / stationary|stationary / stationary|stationery / stationery",0,"Stationary = still; stationery = paper.","Diction"),
("An indirect reference to a work is an","allusion|illusion|elusion|delusion",0,"An 'allusion' references another work.","Diction"),
("A ___ employee is one expected to join soon.","perspective|prospective|prospers|prospectus",1,"'Prospective' = future/expected.","Diction"),
("A judge must be ___ (impartial).","disinterested|uninterested|interested|dis-interesting",0,"'Disinterested' = impartial.","Diction"),
("'Not only did she win, ___ she broke the record.'","but also|and|but|so",0,"The correlative pair is 'not only... but also'.","Correlatives"),
("'Between you and ___, the plan is risky.'","I|me|myself|mine",1,"Object of preposition: 'me'.","Pronouns"),
("Who' is used for people; ___ is used for things.","whom|which|that|who's",1,"'Which' for things; 'that' also restricts things.","Pronouns"),
("In a list of three, use the ___ degree of an adjective: 'the ___ of the three'.","comparative|superlative|positive|absolute",1,"Among three or more, superlative.","Usage"),
("'The data ___ published monthly.' Choose the convention used in scientific writing.","is|are|was|has been",1,"In formal statistics usage, plural 'are' is common for data.","Agreement"),
("'If she ___ studied, she would have passed.'","had|has|would have|did",0,"Past perfect in the unreal conditional.","Verb tense"),
("'___ the rain, the match continued.' Choose the best preposition.","Despite of|Despite|Although|In spite",1,"'Despite' takes no 'of'.","Usage"),
("Which idiom is correct?","comply to|comply with|comply for|comply at",1,"'Comply with' is the standard collocation.","Usage"),
("Which is correct?","capable to do|capable of doing|capable in doing|capable for doing",1,"'Capable of' + gerund.","Usage"),
("'Her drawings compare ___ Rembrandt's.' For general comparison:","to|with|at|for",1,"'Compare with' examines similarities/differences.","Usage"),
("'Hardly had she left ___ the phone rang.'","than|when|then|that",1,"'Hardly... when' pairs.","Usage"),
("Which revision best combines: 'The storm hit. The power failed.'","The storm hit and the power failed.|The storm hit, the power failed.|Hitting the storm, power failed.|The storm hit so the power failed and.",0,"The comma-splice-free compound with 'and'.","Sentence structure"),
("Where should this sentence go: 'This method, however, failed.' A 'however' signals","continuation of the same idea|contrast with the previous statement|a conclusion|an example",1,"'However' marks contrast.","Organization"),
("A topic sentence usually appears","last|first in the paragraph|nowhere|only in conclusions",1,"It states the paragraph's main idea up front.","Organization"),
("To support a claim with evidence, pick the choice that","restates the claim|gives a specific relevant fact or example|changes the topic|praises the author",1,"Evidence must concretely support the claim.","Reading"),
("If an author describes a proposal as 'so-called' and 'purportedly', the tone is","enthusiastic|skeptical|neutral|admiring",1,"Scare quotes and 'purportedly' signal doubt.","Reading"),
("An inference question asks for a statement that","must be literally stated|follows reasonably from the passage|contradicts the passage|is your opinion",1,"Inferences are supported, not stated.","Reading"),
("In 'plastic' describing rules, the word means","made of plastic|flexible and adaptable|cheap|permanent",1,"'Plastic' figuratively means malleable.","Vocabulary in context"),
("A chart shows sales rising steeply in Q4. Which claim is supported?","Q4 sales fell|Q4 sales grew sharply|Q4 was stable|Q4 doubled last year",1,"Only the steep rise is shown; causes and comparisons are not.","Graphics"),
("Which punctuation joins two closely related independent clauses?","a comma alone|a semicolon|a hyphen|an apostrophe",1,"Semicolons link independent clauses cleanly.","Punctuation"),
("Which sentence places the modifier correctly?","Wearing a hat, the sun burned Tom.|Wearing a hat, Tom escaped the sun.|The sun, wearing a hat, burned Tom.|Burned by the hat, Tom wore the sun.",1,"The modifier must describe Tom.","Modifiers"),
("The word 'notwithstanding' means","because|despite|however late|in addition to",1,"'Notwithstanding' = in spite of.","Vocabulary in context"),
("Which comparison is correct?","Her score was better than me.|Her score was better than mine.|Her score was better than I.|Her score was more good.",1,"Compare score with score: 'mine'.","Usage"),
("Which sentence keeps the emphasis on the doer?","The window was broken by the boys, who then ran.|The boys broke the window and then ran.|Breaking the window, running happened.|The window having broken, boys ran.",1,"Active voice names the actor directly.","Style")
]